### ISSUE TITLE
Format kcat and Km with subscripts in column headings of AG-grid tables

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#102]
`kcat` --> `k<sub>cat</sub>`
`Km` --> `K<sub>M</sub>`

**Comment by jonrkarr** [comment]
This is more difficult than it should be. See example:
- https://www.ag-grid.com/javascript-grid-header-rendering/
- https://github.com/ag-grid/ag-grid-react-example/blob/67fdecbe5148da750b7a18219b7c7f05f3bdaab1/src-examples/richGridDeclarativeExample/RichGridDeclarativeExample.jsx
- https://github.com/ag-grid/ag-grid-react-example/blob/67fdecbe5148da750b7a18219b7c7f05f3bdaab1/src-examples/richGridDeclarativeExample/SortableHeaderComponent.jsx

**Comment by yosefdroth** [comment]
kcat and km only get displayed in the data section because it's specific to each experimental observation

**Comment by jonrkarr** [comment]
I corrected the formatting for the tool tip labels and updated the discussion above

**Comment by jonrkarr** [comment]
Formatted column headings

Todo: format filter labels

**Comment by jonrkarr** [comment]
Done
