### ISSUE TITLE
Display stats about both all and selected in stats tool panel

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#104]
The stats below the plot are now formatted as a table. Add a third column so that stats are displayed both about all of the data points and just the selected points.

**Comment by yosefdroth** [comment]
It now looks like this: 
![Picture1](https://user-images.githubusercontent.com/20002366/73368537-25c26c80-427f-11ea-85b6-f31857b4b085.png)
Is this good?

**Comment by jonrkarr** [comment]
- Change "Total" --> "All" to be consistent with the axis label of the chart.
- Split range into two rows for min and max. This is easier to format.
- Format the values to a consistent number of significant digits and right align them
- Why is the border for the values blue? I think this should be grey -- could be the same grey as the axes lines

**Comment by jonrkarr** [comment]
Done
