### ISSUE TITLE
Display list of similar metabolites

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#105]
Currently, if the user clicks on a metabolite which only has similar data, it only displays one of the similar metabolites. It should instead display the list of similar metabolites, and the user can filter by tanimoto. It should also inform the user that they are looking at a similar molecule and not the one they searched for. 

See - https://datanator.info/metabolite/Phosphoribosyl-ATP/Escherichia When searching for Phosphoribosyl-ATP, only AMP shows up

**Comment by jonrkarr** [comment]
The data table now includes links to pages for the similar metabolites
