### ISSUE TITLE
Search bar organism should update on-type, not just on click

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#108]
There is an non intuitive ui in the following scenario
 - the user types in an organism into the search box
 - the user does not actually click on the autocomplete form, but simply hits enter after the user is done typing
 - the search will go submitted, but it will not include the organism

I think this may have been by design, but this might lead to a confusing result, where the user has to actually click on the autocomplete box to enter in the organism

**Comment by jonrkarr** [comment]
There was not intended. This was due to a typo (`!==` instead of `===`).

I also fixed the ability to navigate the organism menu with arrow keys.
