### ISSUE TITLE
Improve formatting of pathways in metabolite data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#119]

**Comment by yosefdroth** [comment]
done

**Comment by jonrkarr** [comment]
Done
- Formatted as two columns
- Capitalized names
- Reduced spacing before bullets

**Comment by jonrkarr** [comment]
Sorted alphabetically by name

**Comment by jonrkarr** [comment]
- Removed duplicates
- Removed hyperlinks for pathways with KEGG ids
