### ISSUE TITLE
Fix formatting of uncertainty in metabolite data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#123]
`0.0`, `.` uncertainty should be converted to `null`

See example
https://datanator.info/metabolite/TDP-Glucose

**Comment by yosefdroth** [comment]
done

**Comment by jonrkarr** [comment]
Zeros were still being displayed. Zero uncertainty is unrealistic. This appears to be a problem with ECMDB/YMDB. I replaced these with null (i.e. unknown uncertainty).
