### ISSUE TITLE
Display metadata about the metabolite specified in the URL path for all metabolite data pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#126]
See example https://datanator.info/metabolite/TDP-Glucose. The URL is for TDP-Glucose, but the metadata displayed on the page is about a different metabolite. This is because the REST API needs to return information about the metabolite in the URL (e.g., TDP-Glucose) even if there's no measurements of the concentration of that metabolite.

**Comment by yosefdroth** [comment]
this is solved in yosef-dev3, so this can be closed as soon as its merged

**Comment by jonrkarr** [comment]
Looks god.
