### ISSUE TITLE
Add metadata to protein data pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#147]
- Name
- (KEGG) Pathways

Complete once https://github.com/KarrLab/datanator_rest_api/issues/34 is finished

**Comment by lzy7071** [comment]
Use [/kegg/get_meta/](https://api.datanator.info/kegg/get_meta/?kegg_ids=K00016&kegg_ids=K00018&size=10
) to get meta information on ortholog groups, such as diseases and pathways.

**Comment by jonrkarr** [comment]
Appears to be done
