### ISSUE TITLE
Display links to related resources in data pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#151]
- metabolite 
  --> reactions in which metabolite participates
- RNA
  --> proteins
- Protein
  --> RNA
  --> reactions catalyzed by enzyme
- Reaction
  --> metabolites involved in reaction
  --> proteins which catalyze reaction

**Comment by lzy7071** [comment]
Reaction
 --> Each document now contains an array that indicates which reaction participants can be found in metabolite collections.
 --> Protein information depends on the organism in which the reaction occurs. Documents in reaction_meta index are separated by EC, so I think displaying information (uniprot_id) for reactions on the intermediate page would be messy, as there can be quite a few enzymes from different species. For enzyme information for a specific kinetic law entry, which is specific to an observation, one can use [/ftx/text_search/num_of_index/?query_message=XXX](/ftx/text_search/num_of_index/?query_message=glutamate---cysteine%20ligase&index=protein&from_=0&size=10&fields=protein_name&fields=species), where XXX is the name of the protein.

**Comment by lzy7071** [comment]
- metabolite
 --> [metabolite_meta](https://api.datanator.info/ftx/text_search/num_of_index/?query_message=atp&index=metabolites_meta&from_=0&size=10&fields=reaction_participants.substrates&fields=reaction_participants.products) collection contains information about reactions in which the metabolite participates. The field name is "kinalw_id"

**Comment by lzy7071** [comment]
- Protein
  --> Protein collection now has a field named ["sabio_kinlaw_id"](https://api.datanator.info/proteins/meta/meta_combo/?uniprot_id=Q0KDL6
) to indicate the reactions in which the protein acts as an enzyme (or part of an enzyme complex).

**Comment by jonrkarr** [comment]
@yosefdroth still todo:
- metabolite 
  --> reactions in which metabolite participates

**Comment by jonrkarr** [comment]
This appears to be done
