### ISSUE TITLE
Add sequence similarity columns and filters for RNA and proteins

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#154]
Do once https://github.com/KarrLab/datanator_rest_api/issues/38 is completed

**Comment by lzy7071** [comment]
Use end point '/proteins/similar_protein/refseq/?uniprot_id={}&identity={}' to get similar proteins.

**Comment by jonrkarr** [comment]
Closing. As we discussed, this suggestion doesn't make sense because ortholog groups don't have a well-defined sequence. Consequently, the concept of a distance from an RNA/protein sequence to that of an ortholog group is ill-defined.
