### ISSUE TITLE
Add unit testing for data formatting for metabolite data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#163]
- `src/scenes/BiochemicalEntityDetails/Metabolite/MetadataSection.js` 
  - `formatMetadata`
- `src/scenes/BiochemicalEntityDetails/Metabolite/ConcentrationDataTable.js` 
  - `formatData`

**Comment by jonrkarr** [comment]
Done
- Added testing for concentration data table.

To do
- Add testing for metadata. Follow the examples in `src/__tests__/scenes/BiochemicalEntityDetails/Metabolite.test.js` .

**Comment by yosefdroth** [comment]
done
