### ISSUE TITLE
Add unit testing for data formatting for RNA data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#164]
- `src/scenes/BiochemicalEntityDetails/Rna/MetadataSection.js` 
  - `formatMetadata`
- `src/scenes/BiochemicalEntityDetails/Rna/HalfLifeDataTable.js` 
  - `formatData`

**Comment by jonrkarr** [comment]
Test reference filter

**Comment by yosefdroth** [comment]
done
