### ISSUE TITLE
Add unit testing for data formatting for protein data page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#165]
- `src/scenes/BiochemicalEntityDetails/Protein/MetadataSection.js` 
  - `formatMetadata`
- `src/scenes/BiochemicalEntityDetails/Protein/AbundanceDataTable.js` 
  - `formatData`

**Comment by jonrkarr** [comment]
Use the testing for the metabolite data page as an example. See `src/__tests__/scenes/BiochemicalEntityDetails/Metabolite.test.js`.

**Comment by yosefdroth** [comment]
done
