### ISSUE TITLE
Add tech logos to bottom of home page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#179]
To potentially enable us to take advantage of free resources for open-source projects such as Netlify
https://www.netlify.com/legal/open-source-policy/

**Comment by jonrkarr** [comment]
Done

**Comment by bilalshaikh42** [comment]
Reopening as a reminder to add the netlify badge, as we are now deploying to netlify

**Comment by jonrkarr** [comment]
Have you already updated datanator.info to point to Netlify?

I'll add the Netlify logo.

**Comment by bilalshaikh42** [comment]
It is not pointing there yet. @lzy7071 has access to the DNS records and is working on it.

**Comment by jonrkarr** [comment]
I added the Netlify logo to the home page. I also removed Heroku deployment from the CircleCI build since this will be replaced with Netlify.
