### ISSUE TITLE
Style search results page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#18]
Below are notes about what needs to be improved and specific CSS changes that address most of these issues. I'm also attaching a screenshot of what the page looks like with these changes.

![Datanator](https://user-images.githubusercontent.com/2848297/71213704-3fd15e00-2282-11ea-9354-2d17ef564604.png)

- Color scheme
  - Use consisent color scheme. This is a helpful tool https://paletton.com/#uid=33z0u0kvc++jb+qpd+XPj+VZCGN
  - Background of navigation bar
  - Logo, icons, text in navigation bar
  - Search results
  - box 
- Navigation bar
   - Use new logo in navigation bar
   - Reduce height of logo so there is margin between the logo and the top and bottom of the navigation bar
   - Add help, about links to navigation bar with help, about icons
- Page content
   - Use consistent padding on top, left, bottom, right
- Integrate search bar into navigation bar or remove
- Table of contents
   - Move to left of search results
   - Change to unordered list
   - Remove underlining on hover
   - Change link colors to black
   - Make position "sticky" (see CSS notes below)
- Search results
   - Move to right of search results
   - Visually distinguish each result section
   - Shorten field names (`KEGG ID` --> `KEGG`)
   - Add hyperlinks for each field (e.g., to KEGG, YMDB, ECMDB)
   - Remove undefined ids (e.g., `YMDB ID: undefined`)
   - Replace (`->` with `→` or other arrow)
   - Add pagination
   - Space the results more compactly
- Add spinner or other element to indicate that the user should wait for the search results to load
- HTML metadata
   - Change title to `Datanator: Molecular data for integrative research` or similar
   - Replace favicon with new logo
   - Set additional metadata. Here's an example:
     ```
      <meta name="description" content="Web application for simulating kinetic models of biological processes and visually analyzing their results" />
      <meta name="keywords" content="biomodel, biochemical, molecular, cell, simulate, visualize, reproducible, standards, CellML, SBML, SED-ML, Vega" />
      <meta name="language" content="EN">
      <meta name="copyright" content="Center for Reproducible Biomedical Modeling" />
      <meta name="author" content="Center for Reproducible Biomedical Modeling, info@reproduciblebiomodels.org" />
      <meta name="reply-to" content="info@reproduciblebiomodels.org" />
      <meta name="url" content="https://www.biosimulations.org">
      <meta name="identifier-URL" content="https://www.biosimulations.org">
      ```
- Organization
   - Place all styling into style sheet; do not insert style into HTML
   - Pick meaningful css class names for each HTML DOM element
   - Avoid nesting css classes with itself (e.g., `google results` within `google results`). The inner and outer containers should have different names.
- Use margin rather than `<br/>` to space DOM elements. Only use `<br/>` within paragraphs of text. 

```
/* top navigation bar */
.bp3-navbar.bp3-dark {
    background: #1890ff;
    box-shadow: 0 2px 3px #00000066;
}

.logo-holder {
    height: 46px;
    margin-top: 2px;
    margin-bottom: 2px;
}

.bp3-dark .bp3-button:not([class*=bp3-intent-]) .bp3-icon {
    color: #fff;
}

/* page content */
.general {
    margin: 0 auto;
    margin-top: 50px;
    padding-top: 2rem;
    padding-bottom: 2rem;
    max-width: 1200px;
    display: flex;
    justify-content: space-between;
}
.general > .MuiGrid-root {
    max-width: 15%;
    flex-basis: 15%;
    margin-right: 2rem;    
}

/* search input box */
.ConcSearch {
    display: none !important;
}

/* contents */
.contents {
    color: #333;
    padding: 0.5rem;
    margin: 0 !important;
    border-radius: 4px;
    border: 1px solid #ffc306;
    background: #fffcf2; /* 95% lighten of primary color */
    box-shadow: 3px 3px 5px #00000066;
    position: sticky;
    top: calc(50px + 2rem);
}
.contents h3 {
    margin: 0;
    margin-top: -0.25rem;
    margin-bottom: 0.5rem;
    height: auto;
    padding: 0;
    line-height: 100%;
}
.contents ol {
    list-style-type: circle;
    padding: 0;
    margin: 0;
    margin-left: 1.1rem;
}
.contents a {
    margin-left: -0.125rem;
}
.contents a {
    color: #333;    
}
.contents a:hover {
    text-decoration: none;
}

/* search results */
.general > .google.results {
    width: 100%;
}

.google.results > .MuiGrid-root {
    width: 100%;
    max-width: unset;
    flex-basis: unset;
}
.google.results > .MuiGrid-root > div {
    width: 100%;
    border: 1px solid #1890ff;
    border-radius: 4px;
    background: #f3f9ff;
    box-shadow: 3px 3px 5px #00000066;
}
.google.results > .MuiGrid-root > div:not(:first-child) {
    margin-top: 2rem;
}

.google.results .MuiTypography-h6 {
    color: #fff;
    background: #1890ff;    
    font-weight: bold;
    padding-left: 0.5rem;
    padding-right: 0.5rem;
}

.google.results .MuiList-root {
    width: 100%;
    padding: 1rem;
}

.google.results li {
    padding: 0;
    margin: 0;
}
.google.results li:not(:first-child) {
    margin-top: 1.0rem;
}
.google.results li .MuiListItemText-multiline {
    margin: 0;
}

.google.results li a {
    color: #000;
    font-weight: bold;
    font-size: 1rem;    
}

/* general styling */
br {
    display: none;
}
```

**Comment by jonrkarr** [comment]
The page is looking better. However, I can't comment on most of the page because I don't see any results.

- Logo
  - I saved the logo in SVG format. This can be edited with Inkscape or any text editor. 
  - Stick with the color palette above. In particular, use the orange color FFC306 and a lighter shade (FFCF36 or FFDA66)
- Table of contents 
  - This shouldn't be shown until the results load. The page looks odd with the spinner next to the TOC. 
- Spinner
   - This should be vertically and horizontally centered within the content portion of the page.
- Search bar
  - Should be hidden and only revealed when a search icon (e.g., magnifying glass is clicked).
  - The meaning of the two boxes is still not clear. " in " needs to be inserted in between the two boxes
  - The background color is too dark. Use a lighter shade than 1892FF (e.g., 70BBFD)

**Comment by yosefdroth** [comment]
I made those changes. How is the search results page now? 

Example link - http://datanator.info/general/?q=glucose&organism=Escherichia%20coli

**Comment by jonrkarr** [comment]
Some of the changes have not been made. It is important to address each point of an issue. I have created new issues for items which have not been addressed.

**Comment by jonrkarr** [comment]
Unfortunately, I don't see any results. The server is unavailable. Error 503. I do see that the spinner is centered. That looks nice.

Can you save the page in HTML (Save as --> "Webpage, complete") and attach to the issue?

I think the URL for search results should be renamed (`general` --> `search`)
```
http://datanator.info/search/?q=glucose&organism=Escherichia%20coli
```

**Comment by yosefdroth** [comment]
[Datanator_ Molecular data for integrative research.zip](https://github.com/KarrLab/datanator_frontend/files/4041005/Datanator_.Molecular.data.for.integrative.research.zip)

**Comment by jonrkarr** [comment]
Remaining issues to address
- Change order of sections
  1. Metabolites
  2. Proteins
  3. Reactions

- Protein section
  - Can we display UniProt ids?

- Reaction section
  - Can we EC numbers?
  - Can we display the names associated with the EC numbers?

- Style
  - Align vertical position of first section with TOC
    - Remove "style="margin-top: 10px"
    - Same as comments in #24 
  - Increase vertical spacing between sections
    - Remove "style="margin-top: 10px"
    - Same as comments in #24
  - Polish style of "Load More"
     - Rename "Load More (10+)" to "Load More" or "Load 10 More"
     - Can we indicate the total number of results? E.g. "Load 10 More of XX"
     - Make full width, set background color to light orange, set bottom radius to 3px, set color to gray
        ```
        .google.results button  {
          width: 100%;
          background-color: #ffe69b !important;
          color: rgb(0, 0, 0, 0.54);
          border-bottom-left-radius: 3px;
          border-bottom-right-radius: 3px;
        }
        ```

**Comment by jonrkarr** [comment]
Reordered sections

**Comment by jonrkarr** [comment]
Also display search query

**Comment by jonrkarr** [comment]
Also display number of search results

**Comment by jonrkarr** [comment]
CSS styling done.

Notes about additional content that is needed are now covered by #77, #78, #79, and #80.
