### ISSUE TITLE
Why are data-type specific MetadataSection components exported with withRouter?

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#185]
I noticed that both the BaseMetadataSection and the data-type specific MetadataSection are exported wrapped by default wrapped in withRouter. 

I see that the BaseMetadataSection requires withRouter for the history, but is withRouter necessary in the data-type specific MetadataSection components (e.g. src/scenes/BiochemicalEntityDetails/Protein/MetadataSection)? It would be simpler for testing if it can be exported without the withRouter.

**Comment by jonrkarr** [comment]
You're correct that this isn't necessary. `withRouter` is only needed for classes that need to access the `history` property. I have removed this.
