### ISSUE TITLE
Change the color of "WC | datanator" in the top left corner of the search bar

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#19]
http://datanator.info/general/?q=glucose&organism=Homo%20sapiens

**Comment by yosefdroth** [comment]
I replaced it with the new Datanator icon. Do you think it looks nice with the words "WC Datanator"? is is it good with just the icon?

**Comment by lzy7071** [comment]
I think the logo by itself looks good. But if our lab have other products under "WC" (WC | Biosimulator?), "WC | Datanator" would make sense.

**Comment by jonrkarr** [comment]
This is subsumed by #32 and #42
