### ISSUE TITLE
Temperature/pH overflow in reaction filters

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#190]
See attached screenshot.
![Screenshot from 2020-02-26 12-31-28](https://user-images.githubusercontent.com/45886782/75371051-180b0180-5894-11ea-8492-45ee6396a90b.png)

**Comment by jonrkarr** [comment]
Do you remember which page this occurred on? It should be a page with no temperature or pH information.

**Comment by jonrkarr** [comment]
Done
