### ISSUE TITLE
Filter dont work in combination

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#194]
Right now, if you use one filter, and then use another, the effects of the first filter are cancelled. 

Example to reproduce:
https://datanator.info/metabolite/Adenosine%20triphosphate/Bacillus%20subtilis%20subsp.%20subtilis#concentration

1) Bring taxonomic distance slider all the way down to the last node (bacillus subtilis subsp. subtilis)
2) Move the chemical similarity slider a little bit
The effects of the first filter are cancelled, and it displays results from all organisms.

**Comment by jonrkarr** [comment]
Done
