### ISSUE TITLE
Best way to test JSX using JEST

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#195]
The method MetadataSection.formatMetadata() returns a dictionary. One of the values it returns is a JSX element. What is the best way to test JSX elements in unit testing? If I compare it to other JSX elements, I get errors that seem to be with the spacing. The test was: 

```
expect(formattedMetadata[0].content).toEqual(
      <ul className="key-value-list link-list">
        <li>
          <b>Name:</b>
          Adenylate kinase
        </li>
        <li>
          <b>Equation:</b> AMP + ATP → ADP
        </li>
        <li>
          <b>EC number:</b>{" "}
          <a
            href="https://enzyme.expasy.org/EC/2.7.4.3"
            rel="noopener noreferrer"
            target="_blank"
          >
            2.7.4.3
          </a>
        </li>
      </ul>
    );
```

and error is:

expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -3,23 +3,28 @@
          "content": <ul
            className="key-value-list link-list"
          >
            <li>
              <b>
    -           Name:
    +           Name
    +           :
              </b>
    -          Adenylate kinase
    +          
    +         Adenylate kinase
            </li>
            <li>
              <b>
    -           Equation:
    +           Equation
    +           :
              </b>
    -          AMP + ATP → ADP
    +          
    +         AMP + ATP → ADP
            </li>
            <li>
              <b>
    -           EC number:
    +           EC number
    +           :
              </b>
               
              <a
                href="https://enzyme.expasy.org/EC/2.7.4.3"
                rel="noopener noreferrer"

      71 |     const processedMetadata = MetadataSection.processMetadata(testRawData);
      72 |     const formattedMetadata = MetadataSection.formatMetadata(processedMetadata);
    > 73 |     expect(formattedMetadata).toEqual([
         |                               ^
      74 |       {
      75 |         content: (
      76 |           <ul className="key-value-list link-list">

What I have done instead is use [ReactDOMServer.renderToStaticMarkup()](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) to turn the JSX into static markup language:

```
expect(
      ReactDOMServer.renderToStaticMarkup(formattedMetadata[0].content)
    ).toEqual(
      '<ul class="key-value-list link-list"><li><b>Name:</b> Adenylate kinase</li><li><b>Equation:</b> AMP + ATP → ADP</li><li><b>EC number:</b> <a href="https://enzyme.expasy.org/EC/2.7.4.3" target="_blank" rel="noopener noreferrer">2.7.4.3</a></li></ul>'
    );

```
Is this the best way to compare JSX elements in testing?

**Comment by jonrkarr** [comment]
The Enzyme library from AirBnB makes this easy:
https://enzymejs.github.io/enzyme/docs/api/shallow.html

I used Enzyme in `src/__tests__/utils/utils.test.js`. The `shallow` class provides methods for extracting information from virtual DOM objects which can be used for testing:
- Generate an HTML representation of a virtual DOM object: `shallow(vDomObj).html()`
- Extract the text of a virtual DOM object:  `shallow(vDomObj).text()`
- Get the properties of a virtual DOM objects: `props`
- Extract a child of a virtual DOM object: `find`
- Compare two virtual DOM objects: `equals`
