### ISSUE TITLE
Search on the front page (http://datanator.info/)

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#20]
If I enter "atp" in the left search bar and a random string such as "owers," I get a "no results" in the drop down suggestion and can't navigate to an intermediate page with a link such as http://datanator.info/general/?q=atp&organism=owers.

Instead, I think the search on the front page should just be one field, perhaps in the center of the page. The user input in the field will be passed to separate API calls, either "/num_of_index/" or "/protein_ranked_by_ko/"

**Comment by jonrkarr** [comment]
It is now possible to search with an organism that doesn't match anything in the autocomplete drop down.

See #37 for discussion of further improvements to the search box.
