### ISSUE TITLE
Can the requirement `package.json` be removed?

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#202]
This is the source of the build failure. It doesn't look like we need this. Can it be removed (i.e. `npm uninstall package.json`)?

If it is necessary, the build can be fixed simply by adding `package.json` to the `ignores` section in `.depcheckrc.yml`.

**Comment by lzy7071** [comment]
To which requirement are you referring?

**Comment by jonrkarr** [comment]
Line 82 in `package.json`:
```
"package.json": "^2.0.1",
```

This is to lookup package metadata from NPM. I suspect this was unintentionally added at 085758f2cd9627d110ab05240df8ce827e462d9a.

**Comment by lzy7071** [comment]
That was, indeed, unintentionally added. Although I don't know how it got added. I tried running a local production server with `npm install package.json` Perhaps that was it?
But `"package.json": "^2.0.1",` is definitely not needed.

**Comment by jonrkarr** [comment]
I removed this.

The argument to `npm install` is either (a) a name of a package in NPM or (b) a path to a directory which contains a `package.json` file.
