### ISSUE TITLE
Mention persistent search bar at the top of the webpage. 

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#203]
Because the search interface at the top bar is closed by default, I believe we should let the users know that they could perform a search using the search bar from anywhere on the frontend.

**Comment by jonrkarr** [comment]
This should be added to the help page.

**Comment by lzy7071** [comment]
> This should be added to the help page.

Sorry I forgot to say. I did mean the tutorial section of the help page.

**Comment by jonrkarr** [comment]
Agreed. This is a good place to describe this.

**Comment by jonrkarr** [comment]
@yosefdroth this can be described between steps (1) and (2) of the tutorial at http://localhost:3000/help#tutorial. Please include a search of the search bar in the header.

**Comment by yosefdroth** [comment]
done in stats. Will be added to site in next merge
