### ISSUE TITLE
All names lead to "Uridine triphosphate"

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#21]
From this page: "(http://datanator.info/general/?q=glucose&organism=Homo%20sapiens)", if one were to click on any metabolite name, reaction entries, or protein entries, one would end up on a page for the metabolite named "Uridine triphosphate."

**Comment by yosefdroth** [comment]
I did this temporarily as I update the tables. I will update this soon.

**Comment by yosefdroth** [comment]
updated!
