### ISSUE TITLE
Merging Protein and RNA Pages

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#212]
Hi all, 

Now that we have organized both protein abundance and RNA half life data by KO group, I think we might want to display the data for both in the same data page.

They share the same metadata (the metadata all comes from the KO information), so this can remove redundancy between the pages. It will also get rid of the need to link the RNA page to the Protein page. I think it can also highlight the benefit of integrating the data-types. 

The metadata would be at the top, followed by the Half-life table and then the abundance table. 

What do you think?

Yosef

**Comment by jonrkarr** [comment]
Thats fine with me. We could call this "Genes" rather than "RNAs" or "Proteins".

@lzy7071 thoughts?

**Comment by lzy7071** [comment]
1. What do you plan to name the category?

2. Is identifying mRNA with protein name or kegg orholog group name conventional or is it going to cause confusions for the users?

Otherwise I think that's fine.

**Comment by jonrkarr** [comment]
I think applying orthologs to both mRNA and (single chain) proteins is fine. I think this will be clear to users.

**Comment by lzy7071** [comment]
> I think applying orthologs to both mRNA and (single chain) proteins is fine. I think this will be clear to users.

In that case I am fine with the proposal.

**Comment by jonrkarr** [comment]
Done in  #213
