### ISSUE TITLE
Fix errors in reaction pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#216]
Many of the reaction pages generate errors. For example, 6 of the first 10 search results for "glucose" don't render. I haven't investigated to determine the reasons or whether this is one or more errors.
- http://localhost:3000/reaction/Glucose--%3EGlucose
- http://localhost:3000/reaction/D-Glucose--%3ED-Glucose
- http://localhost:3000/reaction/UDPglucose--%3EUDPglucose
- http://localhost:3000/reaction/Cinnamic%20acid,UDPglucose--%3ECinnamoyl-beta-1-D-glucose,UDP
- http://localhost:3000/reaction/Galactose%201-phosphate,UDPglucose--%3EGalactose,alpha-D-Glucose%201-phosphate,UDP
- http://localhost:3000/reaction/Glucose,Na%2B--%3ENa%2B,Glucose

**Comment by yosefdroth** [comment]
This appears to be an error on the backend:

Glucose --> Glucose:
https://api.datanator.info/reactions/kinlaw_by_name/?substrates=glucose&products=glucose&_from=0&size=10&bound=loose&taxon_distance=true&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D

Glucose + Na+ → Na+ + Glucose
https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=Glucose%7CNa%252B&products=Na%252B%7CGlucose

**Comment by lzy7071** [comment]
> This appears to be an error on the backend:
> 
> Glucose --> Glucose:
> https://api.datanator.info/reactions/kinlaw_by_name/?substrates=glucose&products=glucose&_from=0&size=10&bound=loose&taxon_distance=true&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D
> 
> Glucose + Na+ → Na+ + Glucose
> https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=Glucose%7CNa%252B&products=Na%252B%7CGlucose

Fixed
