### ISSUE TITLE
Differentiate source links from metabolite names

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#22]
Perhaps something to the likes of "Source links: (YMDB: YMDB00146), (ECMDB: M2MDB000145)," with the entire secondary annotation section written in a different color and smaller font size from the metabolite names.

**Comment by yosefdroth** [comment]
I have changed the color to blue, and made them slightly smaller -- http://datanator.info/general/?q=atp&organism=Escherichia%20coli. What do you think of this new format?

**Comment by lzy7071** [comment]
I fear that highlighting source links in blue could overshadow our own link, as in users will click on the source links, not knowing the names of the metabolites are also hyperlinks. But we could test it out  as it is now in the next round of demo.

**Comment by jonrkarr** [comment]
This will be addressed with issue #18.
