### ISSUE TITLE
Server error for some reaction results

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#220]
[example](https://datanator.info/reaction/[Isocitrate%20dehydrogenase%20(NADP%2B)],ATP--%3EADP,[Isocitrate%20dehydrogenase%20(NADP%2B)]%20phosphate/Escherichia%20coli%20E1002)
See [issue reply](https://github.com/KarrLab/datanator_rest_api/issues/51#issuecomment-609925101) (pipe delimited `product` and `substrate` names) for [solution](https://api.datanator.info/reactions/kinlaw_by_name/?substrates=%5BIsocitrate%20dehydrogenase%20%28NADP%2B%29%5D|ATP&products=%5BIsocitrate%20dehydrogenase%20%28NADP%2B%29%5D%20phosphate|ADP&_from=0&size=10&bound=loose&taxon_distance=false&species=homo%20sapiens&projection=%7B%27_id%27%3A%200%2C%20%27kegg_meta.gene_ortholog%27%3A%200%7D).

**Comment by yosefdroth** [comment]
thanks for letting me know! This had to do with an error the way '+' was encoded. I fixed this in the 'stats' branch, and will be solved in the next merge.

**Comment by jonrkarr** [comment]
This appears to be fixed
