### ISSUE TITLE
Paginate <pathways> in metabolite page

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#221]
It seems that sometimes the [`pathways`](https://datanator.info/metabolite/phosphate/Escherichia%20coli%20E1002#pathways) section can be excessively long. Would pagination be an appropriate solution?

**Comment by yosefdroth** [comment]
Yes, that is a good idea. I will have it display 10 rows at a time -- similar to the search page

**Comment by yosefdroth** [comment]
this is done in stats branch, and will be added to the site when its merged.

**Comment by jonrkarr** [comment]
This is done
