### ISSUE TITLE
Only link to metabolites with data

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#222]
On the reactions page, it currently links every metabolite to a metabolite page. 
[example](http://localhost:3000/reaction/Isatin,NADH--%3E2%2C3-Dihydroxyindole,NAD%2B)
However, not all metabolites have data, and therefore they lead to an empty page. Only metabolites with data should have links.

**Comment by jonrkarr** [comment]
This is related to #155

**Comment by yosefdroth** [comment]
solved in update_metab

**Comment by jonrkarr** [comment]
This doesn't appear to solved. 

Example: http://localhost:3000/reaction/Isatin,NADH--%3E2%2C3-Dihydroxyindole,NAD%2B
- The reaction equation has links to all four participants
- The metabolite pages for two of the participants (isatin and 2,3-Dihydroxyindole) have errors
   - isatin: http://localhost:3000/metabolite/PGNRLPTYNKQQDY-UHFFFAOYSA-N
   - 2,3-Dihydroxyindole: http://localhost:3000/metabolite/JXDYKVIHCLTXOP-UHFFFAOYSA-N

If these metabolite pages aren't not intended to be valid, the reaction pages shouldn't have links to these invalid pages.

**Comment by lzy7071** [comment]
> This doesn't appear to solved.
> 
> Example: http://localhost:3000/reaction/Isatin,NADH--%3E2%2C3-Dihydroxyindole,NAD%2B
> 
> * The reaction equation has links to all four participants
> * The metabolite pages for two of the participants (isatin and 2,3-Dihydroxyindole) have errors
>   
>   * isatin: http://localhost:3000/metabolite/PGNRLPTYNKQQDY-UHFFFAOYSA-N
>   * 2,3-Dihydroxyindole: http://localhost:3000/metabolite/JXDYKVIHCLTXOP-UHFFFAOYSA-N
> 
> If these metabolite pages aren't not intended to be valid, the reaction pages shouldn't have links to these invalid pages.

Solution is to use `/metabolites/meta/?inchikey=` endpoint to get meta information and use `/metabolites/concentrations/?inchikey=` for data on concentration. Currently, frontend is still using `/metabolites/concentration/` endpoint, which shouldn't be used at this point.

**Comment by jonrkarr** [comment]
This appears to be addressed now.
