### ISSUE TITLE
Genes section only returns proteins with abundances object

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#226]
At the moment, `Genes` section on the intermediary page only returns proteins with `abundances` object. I think we should include entries without abundances because we have expanded the scope of the section from `Proteins` to `Genes`

**Comment by yosefdroth** [comment]
The call is using the protein_ranked_by_ko (e.g. [ras](https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=ras&from_=0&size=10&fields=entry_name&fields=protein_name&fields=gene_name&fields=entrez_id&fields=ko_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=species_name&fields=uniprot_id&fields=ko_number&fields=ec_number)) call on the backend. This call was initially designed to only return proteins with abundance information. 

You are right that we should now include everything. I think the best approach is to change protein_ranked_by_ko to return all genes (not just genes with abundance data).

**Comment by lzy7071** [comment]
> The call is using the protein_ranked_by_ko (e.g. [ras](https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=ras&from_=0&size=10&fields=entry_name&fields=protein_name&fields=gene_name&fields=entrez_id&fields=ko_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=species_name&fields=uniprot_id&fields=ko_number&fields=ec_number)) call on the backend. This call was initially designed to only return proteins with abundance information.
> 
> You are right that we should now include everything. I think the best approach is to change protein_ranked_by_ko to return all genes (not just genes with abundance data).

Agreed

**Comment by lzy7071** [comment]
[ras](https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=ras&from_=0&size=10&fields=entry_name&fields=protein_name&fields=gene_name&fields=entrez_id&fields=ko_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=species_name&fields=uniprot_id&fields=ko_number&fields=ec_number) now returns entries without `abundances` too. It might cause some `KeyError` related errors.

**Comment by jonrkarr** [comment]
It sounds like @lzy7071 has addressed this by changing the REST API. Can this be closed?

**Comment by lzy7071** [comment]
> It sounds like @lzy7071 has addressed this by changing the REST API. Can this be closed?

My only concern is that there might be some `KeyError` related issues because currently frontend probably assumes `abundances` field always exists.

**Comment by jonrkarr** [comment]
I assume @lzy7071 is referring to L38 of `ProteinAbundanceDataTable.js`. I think this line was file. In any case, I changed the line to more explicitly check for the existence of the `abundances` key.
