### ISSUE TITLE
Rework data retrieval for metabolite-specific pages

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#228]
Currently `/metabolites/concentration/?metabolite={}` is doing most of the heavy work and it generally takes more than 5000ms to finish the call.

- [x] - Because all of our metabolites have `inchi_key`, we can use `inchi_key` to go from intermediate page into a metabolite-specific page. 
`/metabolites/meta/?inchikey=` is now written for the retrieval of relevant metabolite metadata information.

- [x] - I will make a new or repurpose an existing endpoint for the retrieval of specific concentration values of metabolites. 
`/metabolites/concentrations/?inchikey={}` retrieves concentration values specific to one metabolite.

Proximity searches:

- [x] - Because we now have organisms other than `E Coli` or `yeast`, the taxonomic proximity searches will be done similar to `Genes` page (rather than `/taxon/canon_rank_distance_by_name/?name=Escherichia%20coli%20E1002`).
`/metabolites/concentrations/?inchikey={}&species={}&taxon_distance={}` adds taxon distance information. Because it iterates over the `concentrations` array, it can be slow at times.

- [x] - There is no concentration values for [UDP-galactose](https://datanator.info/metabolite/USAZACJQJDHAJH-QFIAFIRLSA-N/Escherichia%20coli%20E1002). But I imagine the metabolite's structurally-similar compounds or organism's siblings' might have concentration values in our database. It doesn't look like such a case was taken into consideration or perhaps I'm missing something.
`/metabolites/concentrations/similar_compounds/?inchikey={}&threshold={}` returns a list of similar compounds' concentrations

EDIT1: Changed `kegg_id` in the first bullet point to `inchikey` because not all metabolites have `kegg_id` or different metabolites can have the same `kegg_id`

EDIT2: Finished writing endpoints for data retrieval on frontend.

**Comment by yosefdroth** [comment]
Would it be possible to return all the the information for similar molecules in a single call? It would make it much easier on the frontend code, and would remove the need for syncronous calls. 

We want to display all the data initially (i.e. the default tanimoto setting is 6.5, not 1), so we would have to make all the calls before creating the table. 

Alternative, we could wait until the user moves the tanimoto filter, but I think it's better to do that the first time, while the user might be looking at the metadata, rather than have it make the table work slowly.

**Comment by lzy7071** [comment]
> Would it be possible to return all the the information for similar molecules in a single call? It would make it much easier on the frontend code, and would remove the need for syncronous calls.
> 
> We want to display all the data initially (i.e. the default tanimoto setting is 6.5, not 1), so we would have to make all the calls before creating the table.
> 
> Alternative, we could wait until the user moves the tanimoto filter, but I think it's better to do that the first time, while the user might be looking at the metadata, rather than have it make the table work slowly.

I'm not sure to what endpoint you were referring, but [`/metabolites/concentrations/similar_compounds/`](http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=XJLXINKUBYWONI-NNYOXOHSSA-O&threshold=0.6
) does return all the concentration information for all similar compounds within a threshold value, with inchikey for each similar compound as the "primary key." 
I am weary of writing a call that returns a lot of information as that reduces responsiveness. As a matter of fact, rather than displaying additional concentration information, improving the responsiveness was actually the original intention of reworking metabolites page because `/metabolites/concentration/?metabolite={}` was retrieving a lot of information in one call. It may be an extreme example but it illustrates my concern. However, I do see your point here. Looking at the columns of [`concentrations table`](https://5ebb31bfceacde0006057768--datanator.netlify.app/metabolite/WQZGKKKJIJFFOK-GASJEMHNSA-N/Escherichia%20coli%20E1002), not "all" information for similar metabolites are needed. Will just the names of the similar compounds suffice? Since inchikey, as well as taxon information, is already contained from the response, the similar compound can be uniquely identified if the user wants a link to the said similar compound. 
As I write to this point, I realized that you might be referring to taxonomic distance information. But it is particularly tricky with similar compounds because given a list of similar compounds, each similar compound has a list of concentrations, each of which has a taxon distance to be calculated. The iteration count becomes N*M.

**Comment by jonrkarr** [comment]
This appears to be partially done. However, the chemical similarity column needs to be fixed (the data is commented out) and the source column needs to be restored.

**Comment by yosefdroth** [comment]
The chemical similarity is fixed in update_metab
We have decided not to restore the source column

**Comment by jonrkarr** [comment]
The source needs to be restored

**Comment by jonrkarr** [comment]
Closing because the remaining issues are covered by #243
