### ISSUE TITLE
Display protein modifications information on `Genes` page

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#232]
The endpoint [/proteins/proximity_abundance/proximity_abundance_kegg/?](https://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K08851&distance=40&anchor=Escherichia%20coli%20E1002) now includes `modifications` object, which describes protein modification information.

**Comment by jonrkarr** [comment]
Done.

Example:
http://localhost:3000/gene/K04388/Escherichia%20coli
