### ISSUE TITLE
Display RNA modifications on `Gene` pages

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#233]

**Comment by lzy7071** [comment]
Related to https://github.com/KarrLab/datanator_rest_api/issues/66#issue-617526239

**Comment by jonrkarr** [comment]
I started a component for RNA modifications. This needs to be connected to the REST endpoint for RNA modifications.

**Comment by lzy7071** [comment]
The rest endpoint has been written: https://github.com/KarrLab/datanator_rest_api/issues/66#issuecomment-632171413
[http://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number={}&_from=0&size=10](http://api.datanator.info/rna/modification/get_modifications_by_ko/?ko_number=K14218&_from=0&size=10)

**Comment by jonrkarr** [comment]
I added a table of RNA modifications to the gene page. This is almost done except for supporting taxonomic filtering, which requires support from the REST API.

When modifications of non-coding RNA are displayed, the protein concentration and modification will not be shown.

**Comment by lzy7071** [comment]
> I added a table of RNA modifications to the gene page. This is almost done except for supporting taxonomic filtering, which requires support from the REST API.
> 
> Examples
> 
> * rRNA: http://localhost:3000/gene/K01977
> * tRNA: http://localhost:3000/gene/K14236
> 
> When modifications of non-coding RNA are displayed, the protein concentration and modification will not be shown.

Taxonomic filtering has been enabled here: https://github.com/KarrLab/datanator_rest_api/issues/66#issuecomment-632360987

**Comment by jonrkarr** [comment]
Done
