### ISSUE TITLE
Many metabolite pages have server errors

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#234]
For example, half of the first 10 search results for "glucose" have errors
- [ ] http://localhost:3000/metabolite/YSYKRGRSMLTJNL-URARBOGNSA-L/Colidextribacter
- [ ] http://localhost:3000/metabolite/WQZGKKKJIJFFOK-DVKNGEFBSA-N/Colidextribacter
- [ ] http://localhost:3000/metabolite/YSYKRGRSMLTJNL-KFQCIAAJSA-N/Colidextribacter
- [ ] http://localhost:3000/metabolite/WQZGKKKJIJFFOK-VFUOTHLCSA-N/Colidextribacter
- [ ] http://localhost:3000/metabolite/HXXFSFRBOHSIMQ-DVKNGEFBSA-N/Colidextribacter

**Comment by lzy7071** [comment]
I tried the links provided but I don't see any errors:
[https://datanator.info/metabolite/YSYKRGRSMLTJNL-URARBOGNSA-L/Colidextribacter](https://datanator.info/metabolite/YSYKRGRSMLTJNL-URARBOGNSA-L/Colidextribacter)
[https://datanator.info/metabolite/WQZGKKKJIJFFOK-DVKNGEFBSA-N/Colidextribacter](https://datanator.info/metabolite/WQZGKKKJIJFFOK-DVKNGEFBSA-N/Colidextribacter)
[https://datanator.info/metabolite/YSYKRGRSMLTJNL-KFQCIAAJSA-N/Colidextribacter](https://datanator.info/metabolite/YSYKRGRSMLTJNL-KFQCIAAJSA-N/Colidextribacter)
[https://datanator.info/metabolite/WQZGKKKJIJFFOK-VFUOTHLCSA-N/Colidextribacter](https://datanator.info/metabolite/WQZGKKKJIJFFOK-VFUOTHLCSA-N/Colidextribacter)
[https://datanator.info/metabolite/HXXFSFRBOHSIMQ-DVKNGEFBSA-N/Colidextribacter](https://datanator.info/metabolite/HXXFSFRBOHSIMQ-DVKNGEFBSA-N/Colidextribacter)
Has it been fixed?

**Comment by jonrkarr** [comment]
These are new errors in the `update_metab` branch.

**Comment by yosefdroth** [comment]
These errors arose because we have no concentration data available for those metabolites, and that was causing an error on the new parser. 

This is now fixed in update_metab

**Comment by yosefdroth** [comment]
I forgot about the species error. This is related to https://github.com/KarrLab/datanator_rest_api/issues/71

Many of the errors arise because the frontend is adding the species to the backend query, but the new  /metabolites/concentrations/similar_compounds/ query does not have a species parameter yet.

**Comment by lzy7071** [comment]
See updates in https://github.com/KarrLab/datanator_rest_api/issues/71
