### ISSUE TITLE
Requests for pages about unknown entities return 404 errors rather than server errors

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#235]
- [x] http://localhost:3000/metabolite/xxx
- [ ] http://localhost:3000/gene/xxx
- [x] http://localhost:3000/reaction/xxx

**Comment by yosefdroth** [comment]
Done in update_metab

**Comment by jonrkarr** [comment]
http://localhost:3000/reaction/xxx works correctly, but the other two do not.

**Comment by jonrkarr** [comment]
Done in `update_metab`
