### ISSUE TITLE
Reaction names are sometimes displayed as "[object Object]"

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#236]
For example: 
- [ ] http://localhost:3000/reaction/1-Pentanol,N%2CN-Dimethyl-4-nitrosoaniline--%3E4-(Hydroxylamino)-N%2CN-dimethylaniline,1-Pentanal/Colidextribacter

**Comment by lzy7071** [comment]
I can't seem to see [it](https://datanator.info/reaction/1-Pentanol,N%2CN-Dimethyl-4-nitrosoaniline--%3E4-(Hydroxylamino)-N%2CN-dimethylaniline,1-Pentanal/Colidextribacter). Has it been fixed?

**Comment by jonrkarr** [comment]
The errors I reported today are in the `update_metab` branch.

**Comment by jonrkarr** [comment]
This error was introduced into the branch by incompletely updating for using InChI keys to link to metabolites. This is now fixed in `update_metab` branch.
