### ISSUE TITLE
Cofactors in reaction page need to be updated for new InChi key metabolite URLs

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#238]
Example:
http://localhost:3000/reaction/1-Hexanol,N%2CN-Dimethyl-4-nitrosoaniline--%3E4-(Hydroxylamino)-N%2CN-dimethylaniline,Hexanal/Colidextribacter

The cofactor URL is http://localhost:3000/metabolite/Zn(2+)/Colidextribacter

**Comment by jonrkarr** [comment]
These is a new problem in the `update_metab` branch.

**Comment by yosefdroth** [comment]
To be solved after - https://github.com/KarrLab/datanator_rest_api/issues/72

**Comment by lzy7071** [comment]
Please use ftx search for the purpose of locating cofactors. See https://github.com/KarrLab/datanator_rest_api/issues/72#issuecomment-631055869 for more details and implementations.

**Comment by lzy7071** [comment]
https://github.com/KarrLab/datanator_rest_api/issues/72 is closed as discussed during the weekly meeting.

**Comment by jonrkarr** [comment]
Switched to forwarding to search results as suggested by @lzy7071.
