### ISSUE TITLE
Taxonomic distance column no longer works for metabolites

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#240]
The taxonomic distance information is no longer available.

**Comment by yosefdroth** [comment]
Will complete after https://github.com/KarrLab/datanator_rest_api/issues/71

**Comment by lzy7071** [comment]
See updates in https://github.com/KarrLab/datanator_rest_api/issues/71

**Comment by lzy7071** [comment]
Endpoint `/metabolites/concentrations/similar_compounds/? `[http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false](http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false)
now contains concentration information on the metabolite itself. Taxon distance information can be toggled on / off.

**Comment by jonrkarr** [comment]
Done
