### ISSUE TITLE
Unable to retrieve taxonomically relevant metabolite concentrations

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#242]
http://localhost:3000/metabolite/KYTPWZMUSLPBJZ-UHFFFAOYSA-O/null

**Comment by lzy7071** [comment]
Endpoint `/metabolites/concentrations/similar_compounds/?` [http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false
](http://api.datanator.info/metabolites/concentrations/similar_compounds/?inchikey=NBSCHQHZLSJFNQ-GASJEMHNSA-N&threshold=0.6&target_species=homo%20sapiens&taxon_distance=false
) now contains concentration information on the metabolite itself.

**Comment by jonrkarr** [comment]
Also covered by #240. Done.
