### ISSUE TITLE
Reaction pages no longer render

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#246]
Example
http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate

Due to problem with REST endpoint
https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=D-Glucose%201-phosphate&products=D-Glucose%206-phosphate

**Comment by lzy7071** [comment]
> Example
> http://localhost:3000/reaction/D-Glucose%201-phosphate--%3ED-Glucose%206-phosphate
> 
> Due to problem with REST endpoint
> https://api.datanator.info/reactions/kinlaw_by_name/?_from=0&size=1000&bound=tight&substrates=D-Glucose%201-phosphate&products=D-Glucose%206-phosphate

I forgot to project out a non json-serializable object when I was changing how taxon distance was obtained. It has been fixed now.

**Comment by jonrkarr** [comment]
Thanks!. Looks good now.
