### ISSUE TITLE
Broaden gene search to cover non-coding RNA

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#249]
Edit `getResultsUrl` in `src/scenes/SearchResults/GeneSearchResultsList.js`

**Comment by jonrkarr** [comment]
Will likely be covered by KarrLab/datanator_rest_api#81

**Comment by lzy7071** [comment]
API endpoint done https://github.com/KarrLab/datanator_rest_api/issues/81#issuecomment-632758172
