### ISSUE TITLE
Change reaction identifiers to not use spaces

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#251]
To start advertising Datantor, I submitted it to a few registries of biology resources. One of these is the Identifiers.org database of namespaces. They accepted our metabolite and gene namespaces. To accept our reaction namespace, we need to disallow spaces.

Two alternative to `{comma-separated-list-of-substrates-names}-->{comma-separated-list-of-product-names}`:
- `{comma-separated-list-of-substrate-inchikeys}-->{comma-separated-list-of-product-inchikeys}`
- Assign a unique id to each reaction

This is not critical. Although our reaction namespace wasn't accepted, Datanator will be findable through Identifiers.org.

**Comment by lzy7071** [comment]
> To start advertising Datantor, I submitted it to a few registries of biology resources. One of these is the Identifiers.org database of namespaces. They accepted our metabolite and gene namespaces. To accept our reaction namespace, we need to disallow spaces.
> 
> Two alternative to `{comma-separated-list-of-substrates-names}-->{comma-separated-list-of-product-names}`:
> 
> * `{comma-separated-list-of-substrate-inchikeys}-->{comma-separated-list-of-product-inchikeys}`
> * Assign a unique id to each reaction
> 
> This is not critical. Although our reaction namespace wasn't accepted, Datanator will be findable through Identifiers.org.

I think the first bullet point is a good idea and can be easily implemented. 
The documents in `sabio_reaction_entries` index / collection already have inchikey information for both products and substrates in `products` and `substrates` fields, correspondingly. So generating the URL for reaction-specific page will just be a matter of changing field names. 
For the reaction-specific page, one just needs to change the endpoint used from `/reactions/kinlaw_by_name/` to `/reactions/kinlaw_by_rxn/`.

**Comment by jonrkarr** [comment]
I've implemented this into the frontend. 

There's just one thing left. The `kinlaw_by_rxn` endpoint needs to support the `taxon_distance` parameter. See karrlab/datanator_rest_api#84.

**Comment by lzy7071** [comment]
> I've implemented this into the frontend.
> 
> There's just one thing left. The `kinlaw_by_rxn` endpoint needs to support the `taxon_distance` parameter. See [KarrLab/datanator_rest_api#84](https://github.com/KarrLab/datanator_rest_api/issues/84).

I just added the requested support.
