### ISSUE TITLE
Add chart of taxonomic distribution of data to stats page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#256]
- Bar chart
- Show bars for the ~10 most frequent organisms and 1 bar for everything else
- Bar length should equal the number of observations in Datanator for each organism

This can be addressed once KarrLab/datanator_rest_api#97 is addressed.

**Comment by lzy7071** [comment]
This is going to be too complex to generate on the fly. Do you mind if the endpoint just returns an object with 11 key/value pairs: `{"species_name": count, ...}`?

**Comment by jonrkarr** [comment]
I don't think its necessary to calculate the statistics dynamically. They can all be calculated periodically and stored somewhere.

11 key/value pairs is perfect.

**Comment by jonrkarr** [comment]
Done
