### ISSUE TITLE
Improve metabolite page

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#26]
Hi all, 

Can you please give feedback on the metabolites page --http://datanator.info/metabconcs/Adenosine%20triphosphate/Escherichia%20coli

**Comment by lzy7071** [comment]
Is it possible for "custom stats" to display the four values in four rows, each row for each value?

**Comment by lzy7071** [comment]
Can the height of the table be increased so that it fills most of the screen?

**Comment by yosefdroth** [comment]
added breaks to "custom stats" and renamed it "consensus"

**Comment by jonrkarr** [comment]
Unfortunately, I don't see the page due to server errors.

**Comment by jonrkarr** [comment]
Rename "consensus" --> "Stats". Consensus is a bit too forward, especially given that the measurements are from scattered organisms and conditions. I think its more accurate to call the box plot a statistical summary of the display/selected measurements. Consensus suggests that Datanator extrapolates measurements to a specific organism. I think this is inaccurate and could irritate some users.

**Comment by jonrkarr** [comment]
- Remove copyright from bottom of page or apply to all pages
- Add 2rem margin to content
  - Organize content into a single `div`
     ```
     <div class="total_container">
       <div class="bp3-navbar bp3-fixed-top bp3-dark navbar">...</div>
       <div class="metabolite_definition_data">...</div>
       <div class="ag_chart">...</div>
     </div>
     ```
     -->
     ```
     <div class="total_container">
       <div class="bp3-navbar bp3-fixed-top bp3-dark navbar">...</div>
       <div class="content">
         <div class="metabolite_definition_data">...</div>
         <div class="ag_chart">...</div>
       </div>
     </div>
      ```
  - Change style
     ```
     .content {
       max-width: 1000px;
       margin: calc(50px + 2rem) auto 2rem auto;
     }

     .metabolite_definition_data {
         margin-top: 0px;
         border-radius: 0px;
     }
     ```
- Set vertical spacing between top section and grid to 2rem
   ```
   .ag_chart {
      margin-top: 2rem;
   }
  ```
- Add same box shadow as section to grid
  ```
   .ag_chart {
      box-shadow: 3px 3px 5px rgba(0,0,0,.4);
  }
  ```
- Change the heading of the top section to the name of the metabolite
- The top section should present metadata about the metabolite
  - Textual description (from ECMDB)
  - Synonyms (from ECMDB)
  - InChI/SMILES
  - Picture of the structure
    - Use can use the NIH service described [here](https://cactus.nci.nih.gov/blog/?p=136) to generate images from InChI or SMILES
  - Chemical formula, charge, molecular weight
  - List of similar metabolites and their tanimoto similarity. This doesn't need to display the chemical formula of each metabolite.
  - List of identifiers in other databases (e.g, ChEBI, KEGG, etc.)
- Format chemical formulas with subscripts  (`<sub>x</sub>`)
- Rename "Consensus" to "Stats"

- Just about the grid I think we should put the title "Intracellular Concentration" in the same style as the heading of the first section

- Grid
  - Disable pivot mode, row groups, aggregate values
  - Disable second header row with filters. This is redundant with the filters tool bar.
  - Make column headings grammatically consisent
     - Concentrations --> Concentration
     - Error --> Uncertainty
     - Tanimoto Similarity --> Chemical Similarity
     - Conditions --> Condition
     - Source Link --> Source
  - Display units of concentrations
  - Reorder columns
    - Move Tanimoto Similarity to before Organism column
    - Move Source Link to last column
  - In Source Link column, display id within source (e.g, ECMDB: XX)
  - Right align concentrations
  - Replace numeric taxonomic distance with semantically meaningful string (genus, class, kingdom, etc.)
  - Set filter types of columns
    - Numeric: concentrations
    - Set: molecule, organism, growth phase
  - Consensus tool
    - Change title "Concentrations" --> "Concentration (&mu;M)"
    - Shorten "Standard deviation" --> "Std Dev"
    - Rename "Total" --> "All"
    - Does the box plot use the same blue as in the color palette we've chosen?

**Comment by jonrkarr** [comment]
Closing because this is now covered by several smaller individual issues.
