### ISSUE TITLE
[Airbrake] [Production] Cannot use 'in' operator to search for 'request' in undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#268]
**Airbrake error:** [#3843](https://karrlab.airbrake.io/projects/275996/groups/2762603494423773843)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot use 'in' operator to search for 'request' in undefined ``
**Where:** `<no information>`
**Occurred at:** Jun 08, 2020 15:59:56 UTC
**First seen at:** Jun 08, 2020 15:59:56 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [http://localhost:3000/search/glucose/Escherichia%20coli%200.1197/](http://localhost:3000/search/glucose/Escherichia%20coli%200.1197/)
**File:** `/PROJECT_ROOT/static/js/main.chunk.js`

**Backtrace:**
```
/PROJECT_ROOT/static/js/main.chunk.js:75202:in 
```

**Comment by jonrkarr** [comment]
This should be fixed

**Comment by karr-lab-daemon** [comment]
*Comment from Airbrake:* Resolved [error](https://karrlab.airbrake.io/projects/275996/groups/2762603494423773843) reoccurred.
