### ISSUE TITLE
Improve proteins page

### ISSUE THREAD

**Issue by yosefdroth** [KarrLab/datanator_frontend#27]
Here is an example link - http://datanator.info/protein/ko/mol/?ko=K02502&organism=Escherichia%20coli

**Comment by lzy7071** [comment]
1. Remove comma after the last uniprot ID.
2. I think "Organ" and "Taxonomic Distance" columns should be displayed by default.
3. What API calls is it using? I'll look into why it is slow to open.

**Comment by yosefdroth** [comment]
1. Comma removed
2. I have displayed organ. I am not sure about taxonomic distance -- we are already displaying the organism, perhaps that is enough. We can discuss this tomorrow
3. It uses two sequential api calls

a) http://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K02502&anchor=Escherichia coli&distance=40&depth=40

b) http://api.datanator.info/proteins/meta/meta_combo?uniprot_id=P74592&uniprot_id=O34459&uniprot_id=B0JS32&uniprot_id=P62359&uniprot_id=Q9K013&uniprot_id=Q9HUM5&

It needs these two because the first call does not have all of the metadata (e.g. protein_name, gene_name). At the moment, it has to be sequential because it needs the first call to know which uniprot ids to query.

**Comment by lzy7071** [comment]
I have added "protein_name" and "gene_name" to API call [/proximity_abundance_kegg](http://api.datanator.info/proteins/proximity_abundance/proximity_abundance_kegg/?kegg_id=K02502&anchor=Escherichia coli&distance=40&depth=40)

**Comment by jonrkarr** [comment]
For now, see comments in #26 (metabolite concentrations page)

**Comment by jonrkarr** [comment]
Closing because this is now covered by multiple smaller issues.
