### ISSUE TITLE
Change `bound` value to `tight` in /reactions/kinlaw_by_rxn/ endpoint

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#270]
Can the `bound` parameter value be changed to `tight` for the `/reactions/kinlaw_by_rxn/` API calls made by the frontend?

**Comment by jonrkarr** [comment]
I changed this in these files:
- `src/scenes/BiochemicalEntityDetails/Reaction/MetadataSection.js`
- `src/scenes/BiochemicalEntityDetails/Reaction/RateConstantsDataTable.js`
- `src/__tests__/scenes/BiochemicalEntityDetails/Reaction.test.js`

This seems to work fine except for reactions for which some metabolites don't have InChI keys. See also KarrLab/datanator_rest_api#1116
