### ISSUE TITLE
Test preview sites should use testapi.datanator.info for API calls

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#271]
[Example](https://5ede570dcdbf80782abc43b8--datanator.netlify.app/reaction/ACFIXJIJDZMPPO-NNYOXOHSSA-N,GPRLSGONYQIRFK-UHFFFAOYSA-N,XLSMFKSTNGKWQX-UHFFFAOYSA-N--%3EDNIAPMSPPWPWGF-UHFFFAOYSA-N,XJLXINKUBYWONI-NNYOXOHSSA-N/Epicephala%20sp.%20ex%20Glochidion%20eriocarpum%20E.eriocarpumC)

**Comment by jonrkarr** [comment]
The REST API endpoint is controlled via `.env*`.

To use testapi.datanator.info, the `NODE_ENV` environment variable should be set to `test` or `development`. This should be set when the "preview" sites are deployed.

**Comment by lzy7071** [comment]
Got it.

**Comment by jonrkarr** [comment]
`NODE_ENV=production` maps to the configuration in the `.env` file. Under production mode, the frontend will use api.datanator.info.
