### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'toUpperCase' of null

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#277]
**Airbrake error:** [#2905](https://karrlab.airbrake.io/projects/275996/groups/2767280101868552905)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'toUpperCase' of null ``
**Where:** `<no information>`
**Occurred at:** Jun 15, 2020 02:51:31 UTC
**First seen at:** Jun 15, 2020 02:51:31 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [http://localhost:3000/metabolite/HXXFSFRBOHSIMQ-VFUOTHLCSA-N/Escherichia%20coli/#concentration](http://localhost:3000/metabolite/HXXFSFRBOHSIMQ-VFUOTHLCSA-N/Escherichia%20coli/#concentration)
**File:** `/PROJECT_ROOT/static/js/main.chunk.js`

**Backtrace:**
```
/PROJECT_ROOT/static/js/main.chunk.js:40934:in Object.formatResults [as format-results]
/PROJECT_ROOT/static/js/main.chunk.js:42527:in 
```

**Comment by jonrkarr** [comment]
Fixed
