### ISSUE TITLE
[Airbrake] [Production] Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#280]
**Airbrake error:** [#0345](https://karrlab.airbrake.io/projects/275996/groups/2768605329957700345)
**Airbrake project:** datanator_frontend

**Error type:** `InvalidStateError`
**Error message:** `` Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob'). ``
**Where:** `<no information>`
**Occurred at:** Jun 16, 2020 22:44:33 UTC
**First seen at:** Jun 16, 2020 22:44:33 UTC
**Occurrences:** 0 (0 since last deploy on Jun 16, 2020 16:12:45 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/A0QQA1/](https://datanator.info/gene/A0QQA1/)
**File:** `https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/bruit-core_4.entry.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/bruit-core_4.entry.js:8481:in responseText
https://datanator.info/src/instrumentation/xhr.ts:41:in 
```

**Comment by jonrkarr** [comment]
This is an error in Bruit

**Comment by karr-lab-daemon** [comment]
*Comment from Airbrake:* Resolved [error](https://karrlab.airbrake.io/projects/275996/groups/2768605329957700345) reoccurred.
