### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'gene_name' of null

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#281]
**Airbrake error:** [#3925](https://karrlab.airbrake.io/projects/275996/groups/2768605320294023925)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'gene_name' of null ``
**Where:** `<no information>`
**Occurred at:** Jun 16, 2020 22:44:24 UTC
**First seen at:** Jun 16, 2020 22:44:24 UTC
**Occurrences:** 0 (0 since last deploy on Jun 16, 2020 16:12:45 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/A0QQA1/](https://datanator.info/gene/A0QQA1/)
**File:** `https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/RnaHalfLifeDataTable.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/RnaHalfLifeDataTable.js:48:in gene_name
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:318:in query
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:183:in formatData
https://datanator.info/static/node_modules/axios/lib/helpers/spread.js:25:in apply
```

**Comment by jonrkarr** [comment]
Fixed
