### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'isProxied' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#283]
**Airbrake error:** [#4505](https://karrlab.airbrake.io/projects/275996/groups/2769049144304714505)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'isProxied' of undefined ``
**Where:** `<no information>`
**Occurred at:** Jun 17, 2020 13:26:13 UTC
**First seen at:** Jun 17, 2020 13:26:13 UTC
**Occurrences:** 0 (0 since last deploy on Jun 17, 2020 02:15:06 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/](https://datanator.info/)
**File:** `https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:1436:in isProxied
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:45:in call
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:26:in 
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:17:in next
```

**Comment by jonrkarr** [comment]
This is an error in bruit. I submitted this as Moventes/bruit.io#69.
