### ISSUE TITLE
[Airbrake] [Production] Invalid regular expression: /^.*?(?<!\/)$/: Invalid group

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#286]
**Airbrake error:** [#0452](https://karrlab.airbrake.io/projects/275996/groups/2770603057306780452)
**Airbrake project:** datanator_frontend

**Error type:** `SyntaxError`
**Error message:** `` Invalid regular expression: /^.*?(?<!\/)$/: Invalid group ``
**Where:** `<no information>`
**Occurred at:** Jun 19, 2020 16:53:32 UTC
**First seen at:** Jun 19, 2020 16:53:32 UTC
**Occurrences:** 0 (0 since last deploy on Jun 17, 2020 16:59:21 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/](https://datanator.info/)
**File:** `https://datanator.info/static/js/index.js`

**Backtrace:**
```
https://datanator.info/static/js/index.js:56:in 
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:153:in c
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:261:in oh
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:246:in Rj
```

**Comment by jonrkarr** [comment]
Fixed. This was implemented requiring negative lookahead which only recent Chrome has. Now its implemented in a way which is more cross-browser compatible.
