### ISSUE TITLE
[Airbrake] [Production] Object doesn't support property or method 'getElementById'

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#288]
**Airbrake error:** [#6230](https://karrlab.airbrake.io/projects/275996/groups/2770673760823526230)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Object doesn't support property or method 'getElementById' ``
**Where:** `<no information>`
**Occurred at:** Jun 19, 2020 19:14:09 UTC
**First seen at:** Jun 19, 2020 19:14:09 UTC
**Occurrences:** 0 (0 since last deploy on Jun 19, 2020 19:13:47 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/help/](https://datanator.info/help/)
**File:** `https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/bruit-core_4.entry.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/bruit-core_4.entry.js:9205:in 
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/bruit-core_4.entry.js:9120:in _this_1
```

**Comment by jonrkarr** [comment]
This is a bruit problem
