### ISSUE TITLE
Dev branch deploy preview on Netlify no longer uses testapi.datanator.info

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#292]
Example: API calls made in https://5eefe4ccb11f51000794e165--datanator.netlify.app/search/atp%20/Escherichia%20coli%20E1002/ are sent to `api.datanator.info` instead of `testapi.datanator.info`. Could commit 3d977113780608597dac508168cce575b9b3b890 be the cause?
I added projection functionality in test REST API as discussed in the mail. I changed the corresponding files in `datanator_frontend` to reflect the changes in REST API. I tried testing the frontend locally on my computer but the `Reaction` category for some reason refuses to work, either on `dev` branch or `master` branch. Attached is the error prompt and the calls made when frontend is run locally on either `dev` branch or `master` branch.
![tempsnip](https://user-images.githubusercontent.com/45886782/85237281-a2ebab00-b3f3-11ea-9133-bb6c5f9c734d.png)
If I cannot be sure that the new testapi will work on the frontend, I will not deploy the changes to production API at `api.datanator.info`. The changes that incorporate projection in FTX can be tested on `testapi.datanator.info` [here](https://testapi.datanator.info/ftx/text_search/num_of_index/?query_message=OC%5BC%40H%5D1OC%28O%29%5BC%40H%5D%28O%29%5BC%40%40H%5D%28O%29%5BC%40%40H%5D1O&index=metabolites_meta&from_=0&size=10&fields=inchi&fields=InChI_Key&fields=smiles&fields=chemical_formula&fields=name&fields=synonyms&fields=description&fields=biocyc_id&fields=cas_registry_number&fields=chebi_id&fields=chemspider_id&fields=hmdb_id&fields=pathways.pathway.name&fields=pathways.pathway.description&fields=pathways.pathway.ecocyc_pathway_id&fields=pathways.pathway.kegg_map_id&fields=pathways.pathway.pathwhiz_id&includes=InChI_Key&includes=name&includes=chebi_id&excludes=s)

**Comment by jonrkarr** [comment]
I haven't changed the REST API address. I did comment out the netlify-cli commands because the cli is not installing anymore. My best guess is that the new version of one of the dependencies is problematic.

**Comment by lzy7071** [comment]
> I haven't changed the REST API address. I did comment out the netlify-cli commands because the cli is not installing anymore. My best guess is that the new version of one of the dependencies is problematic.

I see. When the build was done by netlify-cli, one can set NODE_ENV so the final `build/` folder should have the correct API endpoint. It seems Netlify treats all deployments with the same build command so I don't see an obvious way to set up separate NODE_ENV (`development`, `test`, or `production`) for branch-based deployments. I'll look into why netlify-cli is not installing anymore.

**Comment by jonrkarr** [comment]
I changed the Netlify build to use `scripts/deploy.sh` (this can also be called via `npm run deploy`). I'll change this to use the `development` environment for non-master branches. Netlify sets a few environment variables which I can use to implement this (see [docs](https://docs.netlify.com/configure-builds/environment-variables/#build-metadata)).

Regarding `netlify-cli`, I'm not sure what's going on. I'm having trouble installing it on my local machine as well.

**Comment by jonrkarr** [comment]
I'm trying to debug the other errors I introduced over the last couple days. Hopefully I'll push this in a few minutes.

**Comment by jonrkarr** [comment]
I haven't figured out the `netlify-cli` issue, but I can install it locally as a local package (i.e., without the `-g` option). I'll add `netlify-cli` as a `dev` dependency and uncomment the netlify building in the CircleCI config.

**Comment by jonrkarr** [comment]
I think I got everything fixed. @lzy7071, close the issue if you agree.

**Comment by lzy7071** [comment]
> I think I got everything fixed. @lzy7071, close the issue if you agree.

I'm going to try running it locally. This might be a different issue but the production site https://www.datanator.info is still using the old endpoints where FTX does not project out irrelevant fields.

**Comment by lzy7071** [comment]
> I think I got everything fixed. @lzy7071, close the issue if you agree.

master branch can be run locally with no issue now.
