### ISSUE TITLE
How does one compile a `development` build of the frontend?

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#295]
I have gotten nelify-cli to work on the circle config and removed netlify-cli as a dependency in `package.json.` But I am having trouble compiling a `development` build of the frontend. I trield:

1. setting NODE_ENV to `development`
2. `npm install` and `npm run build`
3. The final build still uses `https://api.datanator.info` rather than `https://testapi.datanator.info` that I was hoping for.

The exact workflow can be seen here https://github.com/KarrLab/datanator_frontend/blob/cad9d5d39b001e59d3c48d0b94154866f5084eeb/.circleci/config.yml#L273

**Comment by jonrkarr** [comment]
(a) `export NODE_ENV=development` only changes environment variables for the current step. This has to be repeated in each step

(b) As an alternative to `export ...`, environment variables can also be managed via the YAML configuration, e.g.
```
- run:
    name: Install package
    environment:
      NODE_ENV: development
```

(c) Its fine to remove `netlify-cli` as a dev dependency. Keeping it would be fine too. Dev dependencies can include packages needed for compilation and testing. Dev dependencies don't become part of the compiled code that users download.

(d) We should try to keep the Airbrake command:
```
curl -X POST -H "Content-Type: application/json" ...
```
This lets Airbrake now that a new version has been released so Airbrake can keep track of the version that users are using.

**Comment by lzy7071** [comment]
> (a) `export NODE_ENV=development` only changes environment variables for the current step. This has to be repeated in each step
> 
> (b) As an alternative to `export ...`, environment variables can also be managed via the YAML configuration, e.g.
> 
> ```
> - run:
>     name: Install package
>     environment:
>       NODE_ENV: development
> ```
> 
> (c) Its fine to remove `netlify-cli` as a dev dependency. Keeping it would be fine too. Dev dependencies can include packages needed for compilation and testing. Dev dependencies don't become part of the compiled code that users download.
> 
> (d) We should try to keep the Airbrake command:
> 
> ```
> curl -X POST -H "Content-Type: application/json" ...
> ```
> 
> This lets Airbrake now that a new version has been released so Airbrake can keep track of the version that users are using.

Thanks! Good to know about the env settings in circle config. I will give this a try.
I will add Airbrake back in once the debugging of builds is finished.

**Comment by jonrkarr** [comment]
Here's the note in the [CircleCI docs](https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-step) about environment variables
> Note: Since every run step is a new shell, environment variables are not shared across steps.

**Comment by lzy7071** [comment]
There still seems to be some issue with compiling a `development` / `test` build. 

In [this](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1371/workflows/789fb498-d7fb-4c0b-ab4f-a4876c10a0ac/jobs/1430) circle test run, I printed out `NODE_ENV` along various steps and the `development` `NODE_ENV` did persist throughout. But the final preview [link](https://5ef0c4ccaaf7e2cd6cfdb57c--datanator.netlify.app/search/atp/Escherichia%20coli%20E1002/) is still using `https://api.datanator.info`.

I tried the same config but setting `NODE_ENV` to `test` in this circle [test](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1372/workflows/fc3cf3ef-b38d-451a-a693-67f176c12649/jobs/1431) but still the final build was using `https://api.datanator.info`

**Comment by lzy7071** [comment]
> There still seems to be some issue with compiling a `development` / `test` build.
> 
> In [this](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1371/workflows/789fb498-d7fb-4c0b-ab4f-a4876c10a0ac/jobs/1430) circle test run, I printed out `NODE_ENV` along various steps and the `development` `NODE_ENV` did persist throughout. But the final preview [link](https://5ef0c4ccaaf7e2cd6cfdb57c--datanator.netlify.app/search/atp/Escherichia%20coli%20E1002/) is still using `https://api.datanator.info`.
> 
> I tried the same config but setting `NODE_ENV` to `test` in this circle [test](https://app.circleci.com/pipelines/github/KarrLab/datanator_frontend/1372/workflows/fc3cf3ef-b38d-451a-a693-67f176c12649/jobs/1431) but still the final build was using `https://api.datanator.info`

To follow up, I think the issue of `NODE_ENV` being a constant `production` has to do with https://github.com/facebook/create-react-app/issues/790

**Comment by lzy7071** [comment]
Resolved in e43d1db7aa2f1b5bfc40da8fb7f1cea32d782050. See https://create-react-app.dev/docs/deployment/#customizing-environment-variables-for-arbitrary-build-environments for more information.

**Comment by jonrkarr** [comment]
Great. Thanks for figuring out that we need to use a different environment variable.

**Comment by lzy7071** [comment]
No problem. I think with the incorporation of projection functionality for FTX, there seems to be a significant performance improvement for displaying intermediate page: [example](https://5ef0e878a2b9310263e72678--datanator.netlify.app/search/OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O/Epicephala%20sp.%20ex%20Glochidion%20eriocarpum%20E.eriocarpumC/)
