### ISSUE TITLE
Create brief developers documentation

### ISSUE THREAD

**Issue by bilalshaikh42** [KarrLab/datanator_frontend#3]
Create documentation for app structure, coding style, and component heirarchy

**Comment by jonrkarr** [comment]
This would helpful.

To do
- Add a brief description of how datanator_frontend is implemented to `README.md` or another `.md` file linked from `README.md`
  - Major packages used: React, AG-grid, FontAwesome (for icons)
  - How files are organized
    - scenes
    - components
    - utils
    - services
    - tests
    - CSS, images: with associated scene/component
  - Coding style
    - Directory, File, Class names: `UpperCamelCase`
    - Variable, method name: `lowerCamelCase`
    - CSS class names: `lower-dash-case`
  - How to:
    - Test package
    - Lint package: `eslint`, `stylelint`
    - Build package
  - Briefly describe deployment workflow (push to GitHub, run tests, deploy if tests pass)
