### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#300]
**Airbrake error:** [#0142](https://karrlab.airbrake.io/projects/275996/groups/2773911008033490142)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'value' of undefined ``
**Where:** `<no information>`
**Occurred at:** Jun 24, 2020 06:25:50 UTC
**First seen at:** Jun 24, 2020 06:25:50 UTC
**Occurrences:** 0 (0 since last deploy on Jun 23, 2020 15:10:57 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/metabolite/GUAHPAJOXVYFON-UHFFFAOYSA-N/Saccharibacillus%20sacchari/](https://datanator.info/metabolite/GUAHPAJOXVYFON-UHFFFAOYSA-N/Saccharibacillus%20sacchari/)
**File:** `https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Metabolite/MetadataSection.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Metabolite/MetadataSection.js:170:in value
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/MetadataSection.js:106:in query
https://datanator.info/static/node_modules/axios/lib/helpers/spread.js:25:in apply
```

**Comment by jonrkarr** [comment]
Fixed
