### ISSUE TITLE
[Airbrake] [Production] undefined is not a function

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#301]
**Airbrake error:** [#5256](https://karrlab.airbrake.io/projects/275996/groups/2773923321780225256)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` undefined is not a function ``
**Where:** `<no information>`
**Occurred at:** Jun 24, 2020 06:50:20 UTC
**First seen at:** Jun 24, 2020 06:50:20 UTC
**Occurrences:** 0 (0 since last deploy on Jun 23, 2020 15:10:57 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/metabolite/GUAHPAJOXVYFON-UHFFFAOYSA-N/Saccharibacillus%20sacchari/](https://datanator.info/metabolite/GUAHPAJOXVYFON-UHFFFAOYSA-N/Saccharibacillus%20sacchari/)
**File:** `https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:182:in render
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:181:in gi
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:263:in fi
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:246:in Rj
```

**Comment by jonrkarr** [comment]
I believe this was fixed along with #300
