### ISSUE TITLE
https://www.ebi.ac.uk being down creates error prompts

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#302]
>*Comment from Airbrake:* Resolved [error](https://karrlab.airbrake.io/projects/275996/groups/2772234753726858138) reoccurred.
>
>_Originally posted by @karr-lab-daemon in https://github.com/KarrLab/datanator_frontend/issues/291#issuecomment-648750300_

Protein meta information cannot be displayed and is shown a constant spinning wheel before dismissing the error prompt. Error caused by [https://www.ebi.ac.uk/proteins/api/proteins?offset=0&size=1&gene=N](https://www.ebi.ac.uk/proteins/api/proteins?offset=0&size=1&gene=N) returning error 400

**Comment by jonrkarr** [comment]
Fixed
