### ISSUE TITLE
[Airbrake] [Production] me(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#305]
**Airbrake error:** [#2932](https://karrlab.airbrake.io/projects/275996/groups/2779166081932182932)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` me(...).then(...).catch(...).finally is not a function ``
**Where:** `<no information>`
**Occurred at:** Jul 01, 2020 12:26:44 UTC
**First seen at:** Jul 01, 2020 12:26:44 UTC
**Occurrences:** 0 (0 since last deploy on Jun 29, 2020 21:06:11 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/search/unc-68/Caenorhabditis%20elegans/](https://datanator.info/search/unc-68/Caenorhabditis%20elegans/)
**File:** `https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js:103:in finally
https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js:70:in fetchResults
https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js:48:in updateStateFromLocation
https://datanator.info/static/node_modules/react-dom/cjs/react-dom.production.min.js:212:in componentDidMount
```

**Comment by jonrkarr** [comment]
This is the same issue as #304
