### ISSUE TITLE
[Airbrake] [Production] JSON5: invalid character 'R' at 1:1

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#313]
**Airbrake error:** [#3691](https://karrlab.airbrake.io/projects/275996/groups/2785079439260763691)
**Airbrake project:** datanator_frontend

**Error type:** `SyntaxError`
**Error message:** `` JSON5: invalid character 'R' at 1:1 ``
**Where:** `<no information>`
**Occurred at:** Jul 09, 2020 16:15:31 UTC
**First seen at:** Jul 09, 2020 16:15:31 UTC
**Occurrences:** 0 (0 since last deploy on Jul 08, 2020 22:54:25 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/K223755050/](https://datanator.info/gene/K223755050/)
**File:** `https://datanator.info/static/node_modules/json5/dist/index.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/json5/dist/index.js:1429:in 
https://datanator.info/static/node_modules/json5/dist/index.js:1371:in syntaxError
https://datanator.info/static/node_modules/json5/dist/index.js:631:in invalidChar
https://datanator.info/static/node_modules/json5/dist/index.js:422:in lexState
```

**Comment by jonrkarr** [comment]
I think this is an issue for the REST API. See KarrLab/datanator_rest_api#120

**Comment by jonrkarr** [comment]
Fixed. The frontend now displays a 404 error.
