### ISSUE TITLE
[Airbrake] [Production] s.substrates is undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#314]
**Airbrake error:** [#4711](https://karrlab.airbrake.io/projects/275996/groups/2788659459472344711)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` s.substrates is undefined ``
**Where:** `<no information>`
**Occurred at:** Jul 14, 2020 14:48:30 UTC
**First seen at:** Jul 14, 2020 14:48:30 UTC
**Occurrences:** 0 (0 since last deploy on Jul 13, 2020 16:39:17 UTC)
**Severity:** `error`

**URL:** [https://5eefe4ccb11f51000794e165--datanator.netlify.app/search/atp%20/Escherichia%20coli%20E1002/](https://5eefe4ccb11f51000794e165--datanator.netlify.app/search/atp%20/Escherichia%20coli%20E1002/)
**File:** `https://5eefe4ccb11f51000794e165--datanator.netlify.app/static/js/scenes/SearchResults/ReactionSearchResultsList.js`

**Backtrace:**
```
https://5eefe4ccb11f51000794e165--datanator.netlify.app/static/js/scenes/SearchResults/ReactionSearchResultsList.js:81:in formattedResult
https://5eefe4ccb11f51000794e165--datanator.netlify.app/static/js/scenes/SearchResults/SearchResultsList.js:92:in 
```

**Comment by lzy7071** [comment]
Old preview build using new api. https://datanator.info/search/atp%20/Escherichia%20coli%20E1002/ is working as intended.
