### ISSUE TITLE
Add page which lists all data sources

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#317]
Detailed list of all immediate sources
- Metabolites
   - ECMB
   - YMDB
   - Individual articles

**Comment by jonrkarr** [comment]
@lzy7071 can you put the a list of the sources and the date/version each was imported here or in another file?

Can you also assemble a list of all of the individual articles that you obtained data from (metabolite concentrations, RNA half-lives)?

**Comment by lzy7071** [comment]
- ECMDB: version 2.0, database last updated 2015-09-13 12:56:05
- YMDB: version 2.0, database lasted updated 2016-09-08 18:34:53 UTC
- PaxDB: version 4.1, time parsed Oct. 2018
- SABIO-RK: database version 2.7, time modified 2019-10-22T20:16:54.164+00:00
- MODOMICS: same version as bpforms
- Protein Ontology (PRO): same version as bpforms

**Comment by jonrkarr** [comment]
@lzy7071 what versions/dates are we using for these sources?
- NCBI Taxonomy
- OrthoDB
- UniProt

**Comment by lzy7071** [comment]
- NCBI Taxonomy: our database was last updated in May of 2020. The Taxon database itself seems to be continuously updated https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/

- OrthoDB: Version 10.1

- UniProt: Latest update was pulled from release 2020_05

**Comment by jonrkarr** [comment]
@lzy7071 is the UniProt version correct? The latest version is 2020_04.What is the last date you pulled UniProt data?

**Comment by jonrkarr** [comment]
I assume you meant 2020_04 and that this was updated the same time as OrthoDB (2020-09-11). I added this info to the about page.

**Comment by lzy7071** [comment]
> I assume you meant 2020_04 and that this was updated the same time as OrthoDB (2020-09-11). I added this info to the about page.

Yes. Sorry about the typo.
