### ISSUE TITLE
Replace `Downloading the Datanator data` in the about page with link to MongoDB dump in S3

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#318]
- [x] Upload to a public archive such as Zenodo
- [x] Update link in `.env`
- [x] Update link in `.env.development`
- [x] Update link in `.env.test`
- [x] Update link in `README.md` for the datanator repo
   ```
   ... The data is also available for download from [Zenodo]().
   ```
- [x] Update link to data license in `src/scenes/About/About.js`
- [x] Update link to data license in `src/scenes/Help/Faq.js`

**Comment by jonrkarr** [comment]
Also upload to one of these archives
- Dryad (300 GB limit)
- Fighshare (5TB limit)
- Zenodo (50 GB limit)

**Comment by lzy7071** [comment]
The first request was done in 8e15d32fc067269171daf1d3e213d2603778a210.

**Comment by lzy7071** [comment]
> Since we're no longer using Quilt, upload to one of these public archives (this can be used instead of S3)
> 
> * Dryad (300 GB limit)
> * Figshare (5TB limit)
> * Zenodo (50 GB limit)

- Figshare has single file size limit.

- Zenodo and Dryad seem fairly similar to each other. Dryad has a required field for `manuscript number`. Zenodo has a few required fields, two of which are `publication title` and `description`. Neither database provides a way to edit the publication as a group. I'm uploading the data package to Zenodo at the moment, it's very slow.

**Comment by jonrkarr** [comment]
Are you uploading this as multiple files? In that case, it would probably
make sense to use a single .tar.gz file.

**Comment by lzy7071** [comment]
I'm uploading it as an archive, which has a file size of ~4.7G

**Comment by jonrkarr** [comment]
Great!

I moved the location of the download to the `.env*` files.

**Comment by lzy7071** [comment]
> Great!
> 
> I moved the location of the download to the `.env*` files.

Awesome! I'll change it to Zenodo once the upload is finished.

**Comment by jonrkarr** [comment]
Thanks!

**Comment by jonrkarr** [comment]
I clarified the format of the download (MongoDB dump)

**Comment by lzy7071** [comment]
> I clarified the format of the download (MongoDB dump)

Strictly speaking, the archive is not a MongoDB [dump](https://docs.mongodb.com/v4.2/reference/program/mongodump/), which requires a lengthy [`mongorestore`](https://docs.mongodb.com/v4.2/reference/program/mongorestore/) process to load the data into MongoDB. Instead, the archive is a snapshot of the data directory of the database, where a user only needed to mount the directory to load the data into the database.

**Comment by jonrkarr** [comment]
Thanks for clarifying. I changed this from "dump" to "snapshot".
