### ISSUE TITLE
[Airbrake] [Production] Connection to Indexed Database server lost. Refresh the page to try again

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#319]
**Airbrake error:** [#5778](https://karrlab.airbrake.io/projects/275996/groups/2798382847585535778)
**Airbrake project:** datanator_frontend

**Error type:** `UnknownError`
**Error message:** `` Connection to Indexed Database server lost. Refresh the page to try again ``
**Where:** `<no information>`
**Occurred at:** Jul 28, 2020 00:47:01 UTC
**First seen at:** Jul 28, 2020 00:47:01 UTC
**Occurrences:** 0 (0 since last deploy on Jul 27, 2020 13:19:40 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/stats/](https://datanator.info/stats/)
**File:** `https://datanator.info/src/notifier.ts`

**Backtrace:**
```
https://datanator.info/src/notifier.ts:141:in 
```

**Comment by jonrkarr** [comment]
This appears to be due an issue with IndexedDB in iOS. More information: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/354.

As suggested by one developer, I switched datanator to use webSQL in iOS.
