### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#320]
**Airbrake error:** [#0348](https://karrlab.airbrake.io/projects/275996/groups/2801104334906050348)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'status' of undefined ``
**Where:** `<no information>`
**Occurred at:** Jul 31, 2020 18:54:16 UTC
**First seen at:** Jul 31, 2020 18:54:16 UTC
**Occurrences:** 0 (0 since last deploy on Jul 27, 2020 13:19:40 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/search/oxidase/](https://datanator.info/search/oxidase/)
**File:** `https://datanator.info/static/js/scenes/BiochemicalEntityDetails/LoadContent.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/LoadContent.js:44:in status
```

**Comment by jonrkarr** [comment]
fixed
