### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'isProxied' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#325]
**Airbrake error:** [#7426](https://karrlab.airbrake.io/projects/275996/groups/2812665847001237426)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'isProxied' of undefined ``
**Where:** `<no information>`
**Occurred at:** Aug 16, 2020 17:44:53 UTC
**First seen at:** Aug 16, 2020 17:44:53 UTC
**Occurrences:** 0 (0 since last deploy on Aug 04, 2020 16:43:45 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/metabolite/WJA-B/](https://datanator.info/metabolite/WJA-B/)
**File:** `https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:1436:in isProxied
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:45:in call
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:26:in 
https://datanator.info/static/node_modules/@bruit/component/dist/esm-es5/core-60c61d30.js:17:in next
```

**Comment by jonrkarr** [comment]
This error is due Bruit

**Comment by karr-lab-daemon** [comment]
*Comment from Airbrake:* Resolved [error](https://karrlab.airbrake.io/projects/275996/groups/2812665847001237426) reoccurred.

**Comment by jonrkarr** [comment]
This error is due to Bruit. I have muted the error.
