### ISSUE TITLE
[Airbrake] [Production] undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#326]
**Airbrake error:** [#9464](https://karrlab.airbrake.io/projects/275996/groups/2814727152575039464)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` undefined is not iterable (cannot read property Symbol(Symbol.iterator)) ``
**Where:** `<no information>`
**Occurred at:** Aug 19, 2020 14:00:16 UTC
**First seen at:** Aug 19, 2020 14:00:16 UTC
**Occurrences:** 0 (0 since last deploy on Aug 18, 2020 14:51:12 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/K01981/](https://datanator.info/gene/K01981/)
**File:** `https://datanator.info/static/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createForOfIteratorHelper.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createForOfIteratorHelper.js:3:in Symbol
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/RnaModificationDataTable.js:32:in rawDatum
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:319:in query
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:183:in formatData
```

**Comment by jonrkarr** [comment]
Fixed

**Comment by karr-lab-daemon** [comment]
*Comment from Airbrake:* Resolved [error](https://karrlab.airbrake.io/projects/275996/groups/2814727152575039464) reoccurred.

**Comment by jonrkarr** [comment]
This issue is fixed. The re-occurrence was from reading the same page again with the same older version of the code.
