### ISSUE TITLE
[Airbrake] [Production] JSON5: invalid character '<' at 1:1

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#327]
**Airbrake error:** [#0254](https://karrlab.airbrake.io/projects/275996/groups/2819042335929780254)
**Airbrake project:** datanator_frontend

**Error type:** `SyntaxError`
**Error message:** `` JSON5: invalid character '<' at 1:1 ``
**Where:** `<no information>`
**Occurred at:** Aug 25, 2020 12:53:46 UTC
**First seen at:** Aug 25, 2020 12:53:46 UTC
**Occurrences:** 0 (0 since last deploy on Aug 19, 2020 19:03:09 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/K00261/](https://datanator.info/gene/K00261/)
**File:** `https://datanator.info/static/node_modules/json5/dist/index.js`

**Backtrace:**
```
https://datanator.info/static/node_modules/json5/dist/index.js:1457:in 
https://datanator.info/static/node_modules/json5/dist/index.js:1429:in message
https://datanator.info/static/node_modules/json5/dist/index.js:708:in c
https://datanator.info/static/node_modules/json5/dist/index.js:509:in multiLineComment
```

**Comment by jonrkarr** [comment]
This appears to have been a transient issue with the REST API returning invalid JSON.
