### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'ec_name' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#328]
**Airbrake error:** [#8267](https://karrlab.airbrake.io/projects/275996/groups/2825001380754868267)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'ec_name' of undefined ``
**Where:** `<no information>`
**Occurred at:** Sep 02, 2020 18:13:22 UTC
**First seen at:** Sep 02, 2020 18:13:22 UTC
**Occurrences:** 0 (0 since last deploy on Aug 19, 2020 19:03:09 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/K05036/Escherichia%20coli%20E1002/](https://datanator.info/gene/K05036/Escherichia%20coli%20E1002/)
**File:** `https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/MetadataSection.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/MetadataSection.js:212:in 
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/LoadContent.js:113:in response
```

**Comment by jonrkarr** [comment]
The UI wasn't properly handling links to related reactions that don't have EC numbers. Fixed in new commit.
