### ISSUE TITLE
Results fetched but error dialogue prompt says otherwise

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#334]
Search for [`dehydrogenase`](https://datanator.info/search/dehydrogenase/Escherichia%20coli%20E1002/) leads to an error prompt. However, the underlying API [endpoint](https://api.datanator.info/ftx/text_search/gene_ranked_by_ko/?query_message=dehydrogenase&from_=0&size=10&fields=ko_name&fields=ko_number&fields=gene_name&fields=gene_name_alt&fields=gene_name_orf&fields=gene_name_oln&fields=entrez_id&fields=protein_name&fields=entry_name&fields=uniprot_id&fields=ec_number) does retrieve formatted results.

**Comment by lzy7071** [comment]
Fixed by using the first element of the `ko_number` array.

**Comment by jonrkarr** [comment]
I believe this is the same as #333.
