### ISSUE TITLE
[Airbrake] [Production] koNumber.toLowerCase is not a function

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#335]
**Airbrake error:** [#6635](https://karrlab.airbrake.io/projects/275996/groups/2834648101646616635)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` koNumber.toLowerCase is not a function ``
**Where:** `<no information>`
**Occurred at:** Sep 16, 2020 01:39:45 UTC
**First seen at:** Sep 16, 2020 01:39:45 UTC
**Occurrences:** 0 (0 since last deploy on Aug 19, 2020 19:03:09 UTC)
**Severity:** `error`

**URL:** [http://localhost:3000/search/dehydrogenase/Escherichia%20coli%20E1002/](http://localhost:3000/search/dehydrogenase/Escherichia%20coli%20E1002/)
**File:** `/PROJECT_ROOT/static/js/main.chunk.js`

**Backtrace:**
```
/PROJECT_ROOT/static/js/main.chunk.js:19751:in Object.formatResults [as format-results]
/PROJECT_ROOT/static/js/main.chunk.js:20545:in 
```

**Comment by lzy7071** [comment]
Local build to debug https://github.com/KarrLab/datanator_frontend/issues/334#issue-702148938
