### ISSUE TITLE
[Airbrake] [Production] Cannot read property '0' of null

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#337]
**Airbrake error:** [#4330](https://karrlab.airbrake.io/projects/275996/groups/2835860911961524330)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property '0' of null ``
**Where:** `<no information>`
**Occurred at:** Sep 17, 2020 17:49:22 UTC
**First seen at:** Sep 17, 2020 17:49:22 UTC
**Occurrences:** 0 (0 since last deploy on Sep 16, 2020 01:46:22 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/search/utp/Homo%20sapiens/](https://datanator.info/search/utp/Homo%20sapiens/)
**File:** `https://datanator.info/static/js/scenes/SearchResults/GeneSearchResultsList.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/SearchResults/GeneSearchResultsList.js:38:in 
https://datanator.info/static/js/scenes/SearchResults/SearchResultsList.js:93:in response
```

**Comment by lzy7071** [comment]
Seems fine now.

**Comment by jonrkarr** [comment]
AirBrake detected this error again yesterday. 

I suspect the root of the problem is that the API is intermittently returning bad data.

I changed `GeneSearchResultsList` in 0274bec043da73776875d816a8ba4289de76dc32 to avoid this issue, even when the API returns bad responses.
