### ISSUE TITLE
Cannot read property 'ec_name' of undefined

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#338]
The error is  generated by https://datanator.info/gene/K05036/. The reason being some reactions, such as the one returned by https://api.datanator.info/proteins/related/related_reactions_by_kegg/?ko=K05036, do not have a specific `EC` associated with them (`      {
        "id": "-.-.-.-",
        "namespace": "ec-code"
      }`), which leads to `ec_meta` object being missing from the original document in the database (`ec_meta` object was created from the `EC` information in `sabio_rk` collection).
The following is an example where the reaction document contains `EC` information and `ec_meta` object: https://api.datanator.info/proteins/related/related_reactions_by_kegg/?ko=K00034

**Comment by jonrkarr** [comment]
This is the same issue as #328. I fixed this in dd337079f9318eda28bd7bf5a7e716aa4a0e4097.q
