### ISSUE TITLE
[Airbrake] [Production] Cannot read property 'doi' of undefined

### ISSUE THREAD

**Issue by karr-lab-daemon** [KarrLab/datanator_frontend#340]
**Airbrake error:** [#1677](https://karrlab.airbrake.io/projects/275996/groups/2840000910889961677)
**Airbrake project:** datanator_frontend

**Error type:** `TypeError`
**Error message:** `` Cannot read property 'doi' of undefined ``
**Where:** `<no information>`
**Occurred at:** Sep 23, 2020 10:54:47 UTC
**First seen at:** Sep 23, 2020 10:54:47 UTC
**Occurrences:** 0 (0 since last deploy on Sep 22, 2020 23:17:26 UTC)
**Severity:** `error`

**URL:** [https://datanator.info/gene/K02841/Colidextribacter/](https://datanator.info/gene/K02841/Colidextribacter/)
**File:** `https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/RnaHalfLifeDataTable.js`

**Backtrace:**
```
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/Gene/RnaHalfLifeDataTable.js:66:in doi
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:319:in query
https://datanator.info/static/js/scenes/BiochemicalEntityDetails/DataTable/DataTable.js:183:in formatData
https://datanator.info/static/node_modules/axios/lib/helpers/spread.js:25:in apply
```

**Comment by jonrkarr** [comment]
This is already fixed by 7a044e2e4f8a6bc4673cb8dbcb6a432b0804480c. As of the occurrence of the error, this hadn't been deployed yet.
