### ISSUE TITLE
Add instructions for using the MongoDB snapshot to the FAQ

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#342]
@lzy7071, I started a FAQ for instructions for using the MongoDB snapshot. Can you enter the details into `src/scenes/Help/Faq.js`?

I found this documentation: https://docs.mongodb.com/manual/tutorial/backup-with-filesystem-snapshots/. I wasn't sure how you created the snapshot or how it should be restored. Is this restoration something like below

1. Install and configure MongoDB
2. Restore the snapshot
   ```
   lvcreate --size 1G --name mdb-new vg0
   gzip -d -c mdb-snap01.gz | dd of=/dev/vg0/mdb-new
   mount /dev/vg0/mdb-new /srv/mongodb
   ```

**Comment by lzy7071** [comment]
Yes, that's how the restoration should be done. It essentially replaces the currently mounted data partition with the snapshot.

**Comment by jonrkarr** [comment]
I copied the instructions above to the faq.js file. Please edit as needed.

**Comment by lzy7071** [comment]
I added MongoDB's link in https://github.com/KarrLab/datanator_frontend/commit/8a941a5a04652c754a34ea1ba2787b35165dbef7 for details.
