### ISSUE TITLE
Change Zenodo license

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#343]
@lzy7071 Can you please make a few changes to the Zenodo entry (https://doi.org/10.5281/zenodo.3971047)?

- [x] Change the description to something like below:
   > Datanator (https://datanator.info) is an integrated database of genomic and biochemical data designed to help investigators find data about specific molecules and reactions in specific organisms and specific environments for meta-analyses and mechanistic models. For example, Datanator includes metabolite concentrations, RNA modifications and half-lives, protein abundances and modifications, and reaction kinetics integrated from several databases and numerous publications. 
  >
  > We recommend that researchers use the Datanator website and REST API to extracting clouds of data about specific molecules and reactions in specific organisms and specific environments, as well as data about similar molecules and reactions in taxonomically similar organisms.
   >
   > This archive is a copy of the entire Datanator database. This archive is suitable for researchers who wish to analyze the entire database. The archive is a snapshot of the Datanator MongoDB database. Instructions for restoring the snapshot are available at https://datanator.info/help/.

- [x] Set the version to the date (2020.08.03)
- [x] Add keywords: "molecular biology", "systems biology", "computational biology", "bioinformatics", "data integration", "database", "modeling", "simulation"
- [x] Change the license to to `Creative Commons Attribution Non Commercial 4.0 International`
- [x] In the funding section, add 
   - NIH grant P41EB023912
   - NIH grant R35GM119771
- [x] In the related identifiers section, add 
   - https://doi.org/10.1101/2020.08.06.240051
   - "documents this upload"
   - Publication > preprint

**Comment by lzy7071** [comment]
Issue to be done after https://github.com/KarrLab/datanator_frontend/issues/344#issue-707514386

**Comment by jonrkarr** [comment]
@lzy7071 Could you make these changes to the current version in Zenodo?

We'll need to do #344 later this week/next week.

**Comment by lzy7071** [comment]
> @lzy7071 Could you make these changes to the current version in Zenodo?
> 
> We'll need to do #344 later this week/next week.

Done. Funding information was added to `additional notes` section because the `Funding` section only allows OpenAIRE-supported projects only.
License cannot be changed because the dropdown menu does not contain `Creative Commons Attribution Non Commercial 4.0 International`. The most similar one is the current license under `Creative Commons Attribution 4.0 International`

**Comment by jonrkarr** [comment]
Its important to display the correct license. Because we're reusing and re-mixing data, we can't advertise a more permissive license than CC-BY-NC. Please update the license. Zenodo does accept `Creative Commons Attribution Non Commercial 4.0 International`. After you start typing `Creative Commons Attribution....` the dropdown list will display the CC-BY-NC license.

**Comment by lzy7071** [comment]
> Its important to display the correct license. Because we're reusing and re-mixing data, we can't advertise a more permissive license than CC-BY-NC. Please update the license. Zenodo does accept `Creative Commons Attribution Non Commercial 4.0 International`. After you start typing `Creative Commons Attribution....` the dropdown list will display the CC-BY-NC license.

I see. It's done now.

**Comment by jonrkarr** [comment]
Thanks!
