### ISSUE TITLE
The API does not have the correct CORS Setting set to allow for the front end to call the summary data

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#350]
Feedback reported on **Fri Dec 04 2020** at **09:37:11** (GMT-0500)  from **[https://datanator.info/stats/](https://datanator.info/stats/)** 

### Comments

> The API does not have the correct CORS Setting set to allow for the front end to call the summary data

--------------------------------------------------------------------------------------------------

## Context

* Browser : **Chrome 87.0** ([Supported features](https://caniuse.com/#compare=chrome+87))
* Operating System : **Linux x86_64**
* Display : **2560 x 1440** 
* Language : **English** 🇺🇸
* IP / Location : **24.90.234.133** (*[New York, New York, US](https://www.google.com/maps/search/?api=1&query=40.7999,-73.9683)*)
* Network : **10Mbps** (down) / **4g** ([ECT](http://wicg.github.io/netinfo/#effective-connection-types))

 *Generated by Bruit.io. If you like it, let it be known !* [![Github Logo](https://bruit.io/assets/logos/github.png "Github logo")](https://github.com/moventes/bruit.io) [![Twitter Logo](https://bruit.io/assets/logos/twitter.png "Twitter logo")](https://twitter.com/intent/tweet?text=https%3A%2F%2Fbruit.io+is+an+awesome+tool+%21++%23userfeedback+%23bugreporting+%23webdev)

 ⚠ ⚠ ⚠ 

    This feedback was sent with version 1.3.13 of the component while current version is 1.3.14. 

    Please update soon to keep full compatibility. 

    ⚠ ⚠ ⚠ 

![1607092633967.screenshot.png](https://github.com/KarrLab/datanator_frontend_feedback_screenshots/blob/master/1607092633967.screenshot.png?raw=true) 
[1607092636064.application.log](https://github.com/KarrLab/datanator_frontend_feedback_screenshots/blob/master/1607092636064.application.log)

**Comment by lzy7071** [comment]
There doesn't seem to be an issue on my end.

**Comment by jonrkarr** [comment]
This feedback was submitted by someone else with bruit. Looks fine to me.
