### ISSUE TITLE
Improve the usability of search box in top bar

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#43]
- After a user selects an organism in the organism autocomplete results, the focus of the mouse pointer should be returned to the organism input box.
  - Add a click handler. The action of the handler should be to set the focus to the organism input box.
- Clicking enter while the pointer focus is on the organism autocomplete results should result in selecting an organism rather than submitting the search form. 
   - Combined with the next point, perhaps its easier to just disable the handler which causes the form to be submitted when the user types the enter key.
- Add a "search" button at the right side of the "organism" input box to make it clearer to users how to submit a search

**Comment by yosefdroth** [comment]
I see two possibilities for how the enter can work in the search box:
1) the first enter fills the autocomplete, and the second enter submits the query
2) only clicking on the search icon submits the query, enter only fills the autocomplete

What do you all think?

**Comment by jonrkarr** [comment]
- Added a "search" button at the right side of the "organism" input box to make it clearer to users how to submit a search
- Disabled submission when query is empty

**Comment by jonrkarr** [comment]
Done
