### ISSUE TITLE
Add content to help page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#69]
This can be done after the advisory board meeting.

Content
- Brief tutorial
- FAQ
  - How do I contribute data?
- Contact info for more questions

Tasks
- Create directory and files for page in `src/scenes/Help`
  - `src/scenes/Help/Help.js`
  - `src/scenes/Help/Helps.scss`
- Add to navigation in `src/components/Header/Header.js`
- Import and add to router in `src/index.js`

**Comment by jonrkarr** [comment]
I started a page for help, added it to the router, and added a link to the page from the header.

To start, the page contains a brief tutorial, two FAQ, styles for FAQ, and contact info for further questions.

Todo
- Make tutorial more detailed
- Added more FAQ

**Comment by yosefdroth** [comment]
What did you have in mind for the tutorial? Should I provide a specific example? I could add an example similar to what I presented for the demo, and use screenshots of the web pages to demonstrate it.

**Comment by jonrkarr** [comment]
Yes, similar content to the presentation last week for the advisory board would work well. This would work well as screen shots. 

When you make the screen shots, it may be helpful to zoom in with your browser so the text size is larger.

There's many browser plugins that make it easy to take screenshots. Example:
https://chrome.google.com/webstore/detail/nimbus-screenshot-screen/bpconcjcammlapcogcnnelfmaeghhagj?hl=en

**Comment by yosefdroth** [comment]
done

**Comment by jonrkarr** [comment]
FAQs still need to be added. I created a new issue for this (#204).
