### ISSUE TITLE
Add content to statistics page

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/datanator_frontend#73]
- Route: `/stats/`
- Files to be created:
  - `src/scenes/Stats/Stats.js`
  - `src/scenes/Stats/Stats.scss`

**Comment by jonrkarr** [comment]
I created a skeleton for a page for stats, added it to the router, and added a link from the header.

Todo:
- Add content to `src/scenes/Stats/Stats.js`
- Add any necessary styles to `src/scenes/Stats/Stats.scss`

**Comment by jonrkarr** [comment]
- Bar chart of amount of data of each type
   - Metabolite concentrations
   - RNA half-lives
   - Protein abundance
   - Reaction velocities (kcat)
   - Reaction  (Km)
- Bar chart of amount of data by source:
   - ECMDB
   - Individual publications (RNA half-lives)
   - PAXdb
   - SABIO-RK
   - YMDB
- Bar chart of number of observations of each taxon
   - Display ~20 bars for most frequently observed taxa + 1 bar for everything else
   - This could be shown for the database as a whole, or separately for each type of data
- Bar chart of percent completeness of various metadata
   - Cell type (RNA half-lives)
   - Genetic variant (reactions kinetic parameters)
   - Growth phase (metabolite concentrations)
   - Media (metabolite concentrations)
   - Temperature (reactions kinetic parameters)
   - pH (reactions kinetic parameters)
   - Experimental conditions (metabolite concentrations)
- Bar chart of number of referenced journal articles by data type (as best as possible it is to extract this 
information)
   - Metabolite concentrations
   - RNA half-lives
   - Protein abundance
   - Reaction velocities (kcat)
   - Reaction  (Km)

**Comment by jonrkarr** [comment]
@yosefdroth @lzy7071 please add any thoughts on stats to show.

I'm suggesting bar charts because I think that will well for the information we want to show. Other chart types could potentially work as well (e.g., pie chart), but the wedge labels might be too long for a pie chart to display nicely.

Feel free to use any library for generating the charts. One suggestion is Vega-lite.

**Comment by lzy7071** [comment]
I will as I work down the list.

**Comment by lzy7071** [comment]
* Bar chart of amount of data of each type
  * [Metabolite concentrations](https://api.datanator.info/metabolites/summary/concentration_count/
)
  * [RNA half-lives](https://api.datanator.info/rna/meta/get_total_docs/)
  * [Protein abundance](https://api.datanator.info/proteins/summary/num_abundances/)
  * [Reaction velocities (kcat)](https://api.datanator.info/reactions/summary/num_parameter_km/)
  * [Reaction (Km)](https://api.datanator.info/reactions/summary/num_parameter_km/)

**Comment by lzy7071** [comment]
* Bar chart of amount of data by source:
  * ECMDB
  * Individual publications (RNA half-lives)
  * PAXdb: this could be either the same as [Protein abundance](https://api.datanator.info/proteins/summary/num_abundances/) or the number of primary sources used by PAXdb.
  * SABIO-RK
  * YMDB

**Comment by lzy7071** [comment]
* Bar chart of percent completeness of various metadata
  * Cell type (RNA half-lives)
  * Genetic variant (reactions kinetic parameters): this seems a bit redundant since in sabio-rk, a genetic variant is either wildtype or mutant. But if we were to list out each unique reaction's genetic variants, there'd be thousands of data points.
  * Growth phase (metabolite concentrations)
  * Media (metabolite concentrations)
  * Temperature (reactions kinetic parameters)
  * pH (reactions kinetic parameters)
  * Experimental conditions (metabolite concentrations)

**Comment by lzy7071** [comment]
* Bar chart of number of referenced journal articles by data type (as best as possible it is to extract this information)
  * [Metabolite concentrations](https://api.datanator.info/metabolites/summary/get_ref_count/)
  * [RNA half-lives](https://api.datanator.info/rna/summary/get_distinct/?_input=halflives.reference.doi)
  * [Protein abundance](https://api.datanator.info/proteins/summary/num_publications/)
  * Reaction velocities (kcat)
  * Reaction (Km)

**Comment by yosefdroth** [comment]
to do:
add frequency plot for temperature and pH

**Comment by lzy7071** [comment]
> to do:
> add frequency plot for temperature and pH

[pH frequency](https://datanator.info/reactions/summary/get_frequency/?field=ph)
[temperature frequency](https://datanator.info/reactions/summary/get_frequency/?field=temperature)

**Comment by yosefdroth** [comment]
Thanks Yang!

For the bar chart of percent completeness of various metadata, can it output a single number corresponding to the percent?

**Comment by lzy7071** [comment]
> Thanks Yang!
> 
> For the bar chart of percent completeness of various metadata, can it output a single number corresponding to the percent?

That would require iterating through the list, which could be done on the frontend. But I imagined any graphing tool with a pie chart application can do the percentage conversion automatically, no?
