### ISSUE TITLE
Polish color scheme

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#75]
![Screenshot from 2020-01-19 19-12-01](https://user-images.githubusercontent.com/45886782/72691016-e9a94200-3aef-11ea-9fef-a7eb0cb0363a.png)

I think the slightly dark blue contrast better against the yellow of the logo.

**Comment by jonrkarr** [comment]
I prefer the brighter blue. Can we changed the orange? 

The colors (except for those in SVG images) are defined `src/colors.scss`.  This makes it easy to experiment with changes.

**Comment by lzy7071** [comment]
I'll give it a try. It's just bright blue and bright yellow seemed a bit cartoonie to me. If the yellow was turned to orange, I think it'd look better too. Then again, these things are all subjective.
Thanks for that change. I had to do a global search and replacement before.

-------- Original Message --------

**Comment by jonrkarr** [comment]
The color scheme is very subjective. Lets try to get some feedback from others.

**Comment by jonrkarr** [comment]
Closing until we get feedback
