### ISSUE TITLE
Clicking "load 10 more" in "Protein ortholog groups" does not display additional information

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#85]
The pagination for the [API](https://api.datanator.info/#/FTX/get_ftx_text_search_protein_ranked_by_ko_) calls has been fixed and deployed. However, when I tried it out on the front end, clicking "Load 10 more" doesn't display the additional information even though the proper API call is being received by the API server.

**Comment by jonrkarr** [comment]
The API call returns results when `from_`=0, but not when `from_`=10. Did you change the query arguments?

https://api.datanator.info/ftx/text_search/protein_ranked_by_ko/?query_message=fructose&from_=10&size=10&fields=protein_name&fields=synonyms&fields=enzymes&fields=ko_name&fields=gene_name&fields=name&fields=enzymes.enzyme.enzyme_name&fields=enzymes.subunit.canonical_sequence&fields=species

```
{
  "top_kos": {
    "buckets": [],
    "doc_count_error_upper_bound": 0,
    "sum_other_doc_count": 0
  }
}
```

**Comment by lzy7071** [comment]
I set "from_" in this API to indicate the page number (0-indexed). So with the parameter set to from_=10 and size=10, the API is trying to display the 101st  - 110th record, which doesn't exist. 
I changed it back to where "from_=n" to mean the nth record.
