### ISSUE TITLE
Search as you type in "organism" search box

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#86]
Please use the following API call for the "search-as-you-type" function in organism search box:
`ftx/text_search/?query_message=XXX&index=taxon_tree&from_=0&size=10&fields=tax_name&_source_includes=tax_name`
where `XXX` indicates input as a user types. Because there are over a million records of taxonomy names, it is not feasible to do a suggest-like function as that requires a manual suggestion entry for each taxonomy name. See [elasticsearch suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-suggesters.html#completion-suggester) for more information.

**Comment by jonrkarr** [comment]
Done.
