### ISSUE TITLE
Inject object embedded SVG images into HTML

### ISSUE THREAD

**Issue by lzy7071** [KarrLab/datanator_frontend#92]

**Comment by jonrkarr** [comment]
The current implementation of external stylesheets for the SVGs doesn't work well with Chrome.

**Comment by jonrkarr** [comment]
I made these alternative changes which improve the behavior in Chrome
- Replaced xml-stylesheet with link
  - This fixes the SVG loading but the images load with black fills before the style rules are processed
- Inlined styles above imported style sheet
  - This causes the images to load with the desired colors
